/*******************************************************************************
 *
 * This file was auto-generated by:
 *
 * autodecoder b77bdaaef09c678ca52eb518bb539971973d4b9c
 * 
 * Built with g++ (Gentoo 4.6.2 p1.4, pie-0.5.0) 4.6.2
 * Libraries: CUDD 2.4.2; LEMON 1.2.1; Xerces-C++ 3.1.1
 *
 * WARNING: Do not edit this file, otherwise your changes will be lost.
 * Please edit the decoder specification instead, and generate a new decoder.
 *
 * Options used:
 * Specification:     decoder.xml
 * Number of stages:  1 (monolithic)
 * Type:              g (graph)
 * Exhaustive test:   yes
 *
 ******************************************************************************/

autodecoder_t32_monolithic_118:
  if ((instruction & (1u << 29)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_117:
  if ((instruction & (1u << 30)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_116:
  if ((instruction & (1u << 31)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_115:
  if ((instruction & (1u << 28)) == 0)
  {
    goto autodecoder_t32_monolithic_114;
  }

autodecoder_t32_monolithic_99:
  if ((instruction & (1u << 27)) == 0)
  {
    goto autodecoder_t32_monolithic_98;
  }

autodecoder_t32_monolithic_64:
  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_t32_monolithic_63;
  }

autodecoder_t32_monolithic_10:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_t32_monolithic_9;
  }

autodecoder_t32_monolithic_7:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_t32_monolithic_5;
  }

autodecoder_t32_monolithic_6:
  if (instruction & (1u << 20))
  {
    *handler = undefinedInstruction;
    return IRC_REPLACE;
  }
  goto autodecoder_t32_monolithic_5;

autodecoder_t32_monolithic_9:
  if ((instruction & (1u << 21)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_8:
  if ((instruction & (1u << 20)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }
  *handler = undefinedInstruction;
  return IRC_REPLACE;


autodecoder_t32_monolithic_63:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_t32_monolithic_62;
  }

autodecoder_t32_monolithic_24:
  if (instruction & (1u << 4))
  {
    goto autodecoder_t32_monolithic_5;
  }

autodecoder_t32_monolithic_23:
  if (instruction & (1u << 7))
  {
    goto autodecoder_t32_monolithic_5;
  }

autodecoder_t32_monolithic_22:
  if (instruction & (1u << 6))
  {
    goto autodecoder_t32_monolithic_5;
  }

autodecoder_t32_monolithic_21:
  if (instruction & (1u << 21))
  {
    goto autodecoder_t32_monolithic_5;
  }

autodecoder_t32_monolithic_20:
  if (instruction & (1u << 5))
  {
    goto autodecoder_t32_monolithic_5;
  }

autodecoder_t32_monolithic_19:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_t32_monolithic_18;
  }

autodecoder_t32_monolithic_11:
  if (instruction & (1u << 24))
  {
    goto autodecoder_t32_monolithic_3;
  }
  goto autodecoder_t32_monolithic_4;

autodecoder_t32_monolithic_18:
  if ((instruction & (1u << 13)) == 0)
  {
    goto autodecoder_t32_monolithic_5;
  }

autodecoder_t32_monolithic_17:
  if (instruction & (1u << 20))
  {
    goto autodecoder_t32_monolithic_5;
  }

autodecoder_t32_monolithic_16:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_t32_monolithic_4;
  }

autodecoder_t32_monolithic_15:
  if ((instruction & (1u << 15)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_14:
  if (instruction & (1u << 26))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_13:
  if ((instruction & (1u << 14)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_12:
  if (instruction & (1u << 12))
  {
    return IRC_SAFE;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");

autodecoder_t32_monolithic_62:
  if (instruction & (1u << 8))
  {
    goto autodecoder_t32_monolithic_39;
  }

autodecoder_t32_monolithic_61:
  if (instruction & (1u << 9))
  {
    goto autodecoder_t32_monolithic_43;
  }

autodecoder_t32_monolithic_60:
  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_t32_monolithic_59;
  }

autodecoder_t32_monolithic_39:
  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_t32_monolithic_38;
  }

autodecoder_t32_monolithic_34:
  if (instruction & (1u << 21))
  {
    goto autodecoder_t32_monolithic_33;
  }
  goto autodecoder_t32_monolithic_25;

autodecoder_t32_monolithic_59:
  if (instruction & (1u << 7))
  {
    goto autodecoder_t32_monolithic_43;
  }

autodecoder_t32_monolithic_58:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_t32_monolithic_57;
  }

autodecoder_t32_monolithic_43:
  if (instruction & (1u << 11))
  {
    goto autodecoder_t32_monolithic_42;
  }

autodecoder_t32_monolithic_38:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_t32_monolithic_37;
  }

autodecoder_t32_monolithic_36:
  if (instruction & (1u << 23))
  {
    goto autodecoder_t32_monolithic_26;
  }

autodecoder_t32_monolithic_35:
  if (instruction & (1u << 20))
  {
    goto autodecoder_t32_monolithic_30;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");

autodecoder_t32_monolithic_37:
  if (instruction & (1u << 23))
  {
    goto autodecoder_t32_monolithic_25;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");

autodecoder_t32_monolithic_57:
  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_t32_monolithic_56;
  }

autodecoder_t32_monolithic_42:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_t32_monolithic_41;
  }

autodecoder_t32_monolithic_33:
  if (instruction & (1u << 23))
  {
    goto autodecoder_t32_monolithic_26;
  }

autodecoder_t32_monolithic_32:
  if ((instruction & (1u << 20)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_31:
  if (instruction & (1u << 24))
  {
    goto autodecoder_t32_monolithic_3;
  }
  goto autodecoder_t32_monolithic_30;

autodecoder_t32_monolithic_41:
  if (instruction & (1u << 23))
  {
    goto autodecoder_t32_monolithic_25;
  }

autodecoder_t32_monolithic_40:
  if (instruction & (1u << 20))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }
  goto autodecoder_t32_monolithic_25;

autodecoder_t32_monolithic_56:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_t32_monolithic_55;
  }

autodecoder_t32_monolithic_26:
  if (instruction & (1u << 20))
  {
    goto autodecoder_t32_monolithic_3;
  }
  goto autodecoder_t32_monolithic_25;

autodecoder_t32_monolithic_55:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_t32_monolithic_54;
  }

autodecoder_t32_monolithic_25:
  if (instruction & (1u << 24))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }
  goto autodecoder_t32_monolithic_3;

autodecoder_t32_monolithic_54:
  if ((instruction & (1u << 13)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_53:
  if ((instruction & (1u << 20)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_52:
  if ((instruction & (1u << 15)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_51:
  if ((instruction & (1u << 19)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_50:
  if ((instruction & (1u << 18)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_49:
  if ((instruction & (1u << 17)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_48:
  if ((instruction & (1u << 16)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_47:
  if (instruction & (1u << 26))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_46:
  if ((instruction & (1u << 14)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_45:
  if ((instruction & (1u << 12)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }
  *handler = t32LdrbInstruction;
  return IRC_REPLACE;


autodecoder_t32_monolithic_98:
  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_t32_monolithic_97;
  }

autodecoder_t32_monolithic_85:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_t32_monolithic_84;
  }

autodecoder_t32_monolithic_79:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_t32_monolithic_72;
  }

autodecoder_t32_monolithic_78:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_t32_monolithic_72;
  }

autodecoder_t32_monolithic_77:
  if (instruction & (1u << 13))
  {
    goto autodecoder_t32_monolithic_72;
  }

autodecoder_t32_monolithic_76:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_t32_monolithic_72;
  }

autodecoder_t32_monolithic_75:
  if ((instruction & (1u << 15)) == 0)
  {
    return IRC_SAFE;
  }

autodecoder_t32_monolithic_74:
  if (instruction & (1u << 26))
  {
    goto autodecoder_t32_monolithic_71;
  }
  *handler = t32MrsInstruction;
  return IRC_REPLACE;


autodecoder_t32_monolithic_84:
  if (instruction & (1u << 21))
  {
    goto autodecoder_t32_monolithic_80;
  }
  goto autodecoder_t32_monolithic_83;

autodecoder_t32_monolithic_97:
  if (instruction & (1u << 25))
  {
    goto autodecoder_t32_monolithic_72;
  }

autodecoder_t32_monolithic_96:
  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_t32_monolithic_92;
  }

autodecoder_t32_monolithic_95:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_t32_monolithic_92;
  }

autodecoder_t32_monolithic_94:
  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_t32_monolithic_92;
  }

autodecoder_t32_monolithic_93:
  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_t32_monolithic_92;
  }

autodecoder_t32_monolithic_90:
  if (instruction & (1u << 21))
  {
    goto autodecoder_t32_monolithic_83;
  }

autodecoder_t32_monolithic_89:
  if (instruction & (1u << 23))
  {
    goto autodecoder_t32_monolithic_80;
  }

autodecoder_t32_monolithic_88:
  if (instruction & (1u << 24))
  {
    goto autodecoder_t32_monolithic_72;
  }

autodecoder_t32_monolithic_87:
  if (instruction & (1u << 15))
  {
    goto autodecoder_t32_monolithic_71;
  }
  *handler = t32AndInstruction;
  return IRC_REPLACE;


autodecoder_t32_monolithic_92:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_t32_monolithic_91;
  }

autodecoder_t32_monolithic_83:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_t32_monolithic_82;
  }

autodecoder_t32_monolithic_81:
  if (instruction & (1u << 24))
  {
    goto autodecoder_t32_monolithic_72;
  }
  goto autodecoder_t32_monolithic_80;

autodecoder_t32_monolithic_82:
  if (instruction & (1u << 24))
  {
    goto autodecoder_t32_monolithic_80;
  }
  goto autodecoder_t32_monolithic_72;

autodecoder_t32_monolithic_91:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_t32_monolithic_72;
  }

autodecoder_t32_monolithic_80:
  if (instruction & (1u << 15))
  {
    goto autodecoder_t32_monolithic_71;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");

autodecoder_t32_monolithic_72:
  if ((instruction & (1u << 15)) == 0)
  {
    return IRC_SAFE;
  }

autodecoder_t32_monolithic_71:
  if ((instruction & (1u << 14)) == 0)
  {
    goto autodecoder_t32_monolithic_70;
  }

autodecoder_t32_monolithic_67:
  if ((instruction & (1u << 12)) == 0)
  {
    *handler = t32BlxImmediateInstruction;
    return IRC_REPLACE;
  }
  *handler = t32BlInstruction;
  return IRC_REPLACE;



autodecoder_t32_monolithic_70:
  if ((instruction & (1u << 12)) == 0)
  {
    *handler = t32BImmediate17Instruction;
    return IRC_REPLACE;
  }
  *handler = t32BImmediate21Instruction;
  return IRC_REPLACE;



autodecoder_t32_monolithic_114:
  if ((instruction & (1u << 27)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_113:
  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_t32_monolithic_112;
  }

autodecoder_t32_monolithic_106:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_t32_monolithic_3;
  }

autodecoder_t32_monolithic_105:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_t32_monolithic_104;
  }

autodecoder_t32_monolithic_102:
  if (instruction & (1u << 23))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_101:
  if (instruction & (1u << 24))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_100:
  if (instruction & (1u << 15))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_30:
  if ((instruction & (1u << 19)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_29:
  if ((instruction & (1u << 18)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_28:
  if ((instruction & (1u << 17)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_27:
  if (instruction & (1u << 16))
  {
    goto autodecoder_t32_monolithic_3;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");

autodecoder_t32_monolithic_104:
  if (instruction & (1u << 23))
  {
    goto autodecoder_t32_monolithic_103;
  }

autodecoder_t32_monolithic_5:
  if (instruction & (1u << 24))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }
  goto autodecoder_t32_monolithic_4;

autodecoder_t32_monolithic_112:
  if ((instruction & (1u << 25)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_111:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_t32_monolithic_110;
  }

autodecoder_t32_monolithic_107:
  if (instruction & (1u << 23))
  {
    goto autodecoder_t32_monolithic_103;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");

autodecoder_t32_monolithic_110:
  if (instruction & (1u << 23))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_109:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_t32_monolithic_108;
  }

autodecoder_t32_monolithic_103:
  if (instruction & (1u << 24))
  {
    goto autodecoder_t32_monolithic_4;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");

autodecoder_t32_monolithic_108:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_t32_monolithic_3;
  }

autodecoder_t32_monolithic_4:
  if (instruction & (1u << 15))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }

autodecoder_t32_monolithic_3:
  if (instruction & (1u << 26))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t32): undefined instruction");
  }
  return IRC_SAFE;



