/*******************************************************************************
 *
 * This file was auto-generated by:
 *
 * autodecoder 1b649cb0a5ef57446cb8c0835236c293517557f5
 * 
 * Built with g++ (Ubuntu/Linaro 4.6.1-9ubuntu3) 4.6.1
 * Libraries: CUDD 2.4.2; LEMON 1.2.1; Xerces-C++ 3.1.1
 *
 * WARNING: Do not edit this file, otherwise your changes will be lost.
 * Please edit the decoder specification instead, and generate a new decoder.
 *
 * Options used:
 * Specification:     decoder.xml
 * Number of stages:  1 (monolithic)
 * Type:              g (graph)
 * Exhaustive test:   yes
 *
 ******************************************************************************/

autodecoder_t16_monolithic_64:
  if ((instruction & (1u << 14)) == 0)
  {
    goto autodecoder_t16_monolithic_63;
  }

autodecoder_t16_monolithic_33:
  if ((instruction & (1u << 15)) == 0)
  {
    goto autodecoder_t16_monolithic_32;
  }

autodecoder_t16_monolithic_11:
  if ((instruction & (1u << 12)) == 0)
  {
    goto autodecoder_t16_monolithic_10;
  }

autodecoder_t16_monolithic_7:
  if (instruction & (1u << 13))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t16): undefined instruction");
  }

autodecoder_t16_monolithic_6:
  if ((instruction & (1u << 11)) == 0)
  {
    return t16BImmediate8Instruction;
  }

autodecoder_t16_monolithic_5:
  if ((instruction & (1u << 9)) == 0)
  {
    return t16BImmediate8Instruction;
  }

autodecoder_t16_monolithic_4:
  if ((instruction & (1u << 10)) == 0)
  {
    return t16BImmediate8Instruction;
  }

autodecoder_t16_monolithic_3:
  if ((instruction & (1u << 8)) == 0)
  {
    return t16BImmediate8Instruction;
  }
  return svcInstruction;



autodecoder_t16_monolithic_10:
  if ((instruction & (1u << 13)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t16): undefined instruction");
  }

autodecoder_t16_monolithic_9:
  if (instruction & (1u << 11))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t16): undefined instruction");
  }
  return t16BImmediate11Instruction;


autodecoder_t16_monolithic_32:
  if (instruction & (1u << 12))
  {
    goto autodecoder_t16_monolithic_13;
  }

autodecoder_t16_monolithic_31:
  if (instruction & (1u << 13))
  {
    return 0;
  }

autodecoder_t16_monolithic_30:
  if (instruction & (1u << 11))
  {
    return 0;
  }

autodecoder_t16_monolithic_29:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_t16_monolithic_28;
  }

autodecoder_t16_monolithic_26:
  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_t16_monolithic_25;
  }

autodecoder_t16_monolithic_21:
  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_t16_monolithic_20;
  }

autodecoder_t16_monolithic_16:
  if ((instruction & (1u << 7)) == 0)
  {
    return t16BxInstruction;
  }
  return t16BlxRegisterInstruction;



autodecoder_t16_monolithic_20:
  if ((instruction & (1u << 2)) == 0)
  {
    return 0;
  }

autodecoder_t16_monolithic_19:
  if ((instruction & (1u << 1)) == 0)
  {
    return 0;
  }

autodecoder_t16_monolithic_18:
  if ((instruction & (1u << 0)) == 0)
  {
    return 0;
  }
  return t16MovInstruction;


autodecoder_t16_monolithic_25:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_t16_monolithic_24;
  }

autodecoder_t16_monolithic_23:
  if (instruction & (1u << 8))
  {
    goto autodecoder_t16_monolithic_22;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t16): undefined instruction");

autodecoder_t16_monolithic_28:
  if (instruction & (1u << 10))
  {
    goto autodecoder_t16_monolithic_27;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t16): undefined instruction");

autodecoder_t16_monolithic_63:
  if ((instruction & (1u << 15)) == 0)
  {
    goto autodecoder_t16_monolithic_62;
  }

autodecoder_t16_monolithic_56:
  if ((instruction & (1u << 12)) == 0)
  {
    return 0;
  }

autodecoder_t16_monolithic_55:
  if ((instruction & (1u << 13)) == 0)
  {
    return 0;
  }

autodecoder_t16_monolithic_54:
  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_t16_monolithic_53;
  }

autodecoder_t16_monolithic_50:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_t16_monolithic_49;
  }

autodecoder_t16_monolithic_46:
  if ((instruction & (1u << 10)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t16): undefined instruction");
  }

autodecoder_t16_monolithic_45:
  if (instruction & (1u << 5))
  {
    goto autodecoder_t16_monolithic_36;
  }

autodecoder_t16_monolithic_44:
  if (instruction & (1u << 4))
  {
    goto autodecoder_t16_monolithic_36;
  }

autodecoder_t16_monolithic_43:
  if (instruction & (1u << 3))
  {
    goto autodecoder_t16_monolithic_36;
  }

autodecoder_t16_monolithic_42:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_t16_monolithic_41;
  }

autodecoder_t16_monolithic_36:
  if (instruction & (1u << 8))
  {
    return t16ItInstruction;
  }
  return t16BkptInstruction;

autodecoder_t16_monolithic_41:
  if ((instruction & (1u << 8)) == 0)
  {
    return t16BkptInstruction;
  }

autodecoder_t16_monolithic_40:
  if (instruction & (1u << 2))
  {
    return t16ItInstruction;
  }

autodecoder_t16_monolithic_39:
  if (instruction & (1u << 1))
  {
    return t16ItInstruction;
  }

autodecoder_t16_monolithic_38:
  if (instruction & (1u << 0))
  {
    return t16ItInstruction;
  }

autodecoder_t16_monolithic_37:
  if ((instruction & (1u << 7)) == 0)
  {
    return 0;
  }
  return t16ItInstruction;



autodecoder_t16_monolithic_49:
  if ((instruction & (1u << 10)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t16): undefined instruction");
  }

autodecoder_t16_monolithic_48:
  if ((instruction & (1u << 8)) == 0)
  {
    return 0;
  }
  return t16LdmInstruction;


autodecoder_t16_monolithic_53:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_t16_monolithic_52;
  }

autodecoder_t16_monolithic_51:
  if (instruction & (1u << 10))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t16): undefined instruction");
  }

autodecoder_t16_monolithic_24:
  if (instruction & (1u << 8))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t16): undefined instruction");
  }

autodecoder_t16_monolithic_22:
  if (instruction & (1u << 7))
  {
    return 0;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t16): undefined instruction");

autodecoder_t16_monolithic_52:
  if (instruction & (1u << 10))
  {
    return 0;
  }
  goto autodecoder_t16_monolithic_27;

autodecoder_t16_monolithic_62:
  if ((instruction & (1u << 12)) == 0)
  {
    goto autodecoder_t16_monolithic_13;
  }

autodecoder_t16_monolithic_61:
  if ((instruction & (1u << 13)) == 0)
  {
    goto autodecoder_t16_monolithic_60;
  }

autodecoder_t16_monolithic_57:
  if (instruction & (1u << 11))
  {
    return 0;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t16): undefined instruction");

autodecoder_t16_monolithic_60:
  if ((instruction & (1u << 11)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t16): undefined instruction");
  }

autodecoder_t16_monolithic_59:
  if (instruction & (1u << 9))
  {
    return 0;
  }

autodecoder_t16_monolithic_58:
  if (instruction & (1u << 10))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t16): undefined instruction");
  }

autodecoder_t16_monolithic_27:
  if (instruction & (1u << 8))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t16): undefined instruction");
  }
  return 0;

autodecoder_t16_monolithic_13:
  if ((instruction & (1u << 13)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (t16): undefined instruction");
  }
  return 0;



