/*******************************************************************************
 *
 * This file was auto-generated by:
 *
 * autodecoder c943bafcade1dfae790bc213ce5144ba2e8755d1-dirty
 * 
 * Built with g++ (Gentoo 4.4.5 p1.3, pie-0.4.5) 4.4.5
 * Libraries: CUDD 2.4.2; LEMON 1.2.1; Xerces-C++ 3.1.1
 *
 * WARNING: Do not edit this file, otherwise your changes will be lost.
 * Please edit the decoder specification instead, and generate a new decoder.
 *
 * Options used:
 * Specification:     arm.xml
 * Number of stages:  1 (monolithic)
 * Type:              g (graph)
 * Exhaustive test:   yes
 *
 ******************************************************************************/

autodecoder_arm_monolithic_793:
  if ((instruction & (1u << 29)) == 0)
  {
    goto autodecoder_arm_monolithic_790;
  }

autodecoder_arm_monolithic_792:
  if ((instruction & (1u << 30)) == 0)
  {
    goto autodecoder_arm_monolithic_790;
  }

autodecoder_arm_monolithic_791:
  if ((instruction & (1u << 31)) == 0)
  {
    goto autodecoder_arm_monolithic_790;
  }

autodecoder_arm_monolithic_744:
  if ((instruction & (1u << 15)) == 0)
  {
    goto autodecoder_arm_monolithic_743;
  }

autodecoder_arm_monolithic_656:
  if ((instruction & (1u << 27)) == 0)
  {
    goto autodecoder_arm_monolithic_655;
  }

autodecoder_arm_monolithic_20:
  if (instruction & (1u << 28))
  {
    goto autodecoder_arm_monolithic_3;
  }
  goto autodecoder_arm_monolithic_19;

autodecoder_arm_monolithic_655:
  if ((instruction & (1u << 12)) == 0)
  {
    goto autodecoder_arm_monolithic_652;
  }

autodecoder_arm_monolithic_654:
  if ((instruction & (1u << 13)) == 0)
  {
    goto autodecoder_arm_monolithic_652;
  }

autodecoder_arm_monolithic_653:
  if ((instruction & (1u << 14)) == 0)
  {
    goto autodecoder_arm_monolithic_652;
  }

autodecoder_arm_monolithic_612:
  if ((instruction & (1u << 28)) == 0)
  {
    goto autodecoder_arm_monolithic_611;
  }

autodecoder_arm_monolithic_77:
  if ((instruction & (1u << 26)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_76:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_75;
  }

autodecoder_arm_monolithic_29:
  if (instruction & (1u << 4))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_28:
  if (instruction & (1u << 24))
  {
    goto autodecoder_arm_monolithic_23;
  }
  goto autodecoder_arm_monolithic_27;

autodecoder_arm_monolithic_75:
  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_74;
  }

autodecoder_arm_monolithic_53:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_27;
  }

autodecoder_arm_monolithic_52:
  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_23;
  }

autodecoder_arm_monolithic_51:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_23;
  }

autodecoder_arm_monolithic_50:
  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_23;
  }

autodecoder_arm_monolithic_49:
  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_23;
  }

autodecoder_arm_monolithic_48:
  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_23;
  }

autodecoder_arm_monolithic_47:
  if (instruction & (1u << 9))
  {
    goto autodecoder_arm_monolithic_23;
  }

autodecoder_arm_monolithic_46:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_22;
  }

autodecoder_arm_monolithic_45:
  if ((instruction & (1u << 16)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_44:
  if ((instruction & (1u << 19)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_43:
  if ((instruction & (1u << 18)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_42:
  if ((instruction & (1u << 17)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_41:
  if (instruction & (1u << 5))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_40:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_39;
  }

autodecoder_arm_monolithic_32:
  if ((instruction & (1u << 20)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_31:
  if ((instruction & (1u << 22)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  return dmbInstruction;


autodecoder_arm_monolithic_39:
  if ((instruction & (1u << 20)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_38:
  if ((instruction & (1u << 3)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_37:
  if ((instruction & (1u << 1)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_36:
  if ((instruction & (1u << 2)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_35:
  if ((instruction & (1u << 0)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_34:
  if ((instruction & (1u << 22)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  return clrexInstruction;


autodecoder_arm_monolithic_74:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_27;
  }

autodecoder_arm_monolithic_73:
  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_23;
  }

autodecoder_arm_monolithic_72:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_23;
  }

autodecoder_arm_monolithic_71:
  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_23;
  }

autodecoder_arm_monolithic_70:
  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_23;
  }

autodecoder_arm_monolithic_69:
  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_23;
  }

autodecoder_arm_monolithic_68:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_67;
  }

autodecoder_arm_monolithic_23:
  if (instruction & (1u << 21))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  goto autodecoder_arm_monolithic_22;

autodecoder_arm_monolithic_67:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_22;
  }

autodecoder_arm_monolithic_66:
  if ((instruction & (1u << 16)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_65:
  if ((instruction & (1u << 19)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_64:
  if ((instruction & (1u << 18)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_63:
  if ((instruction & (1u << 17)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_62:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_61;
  }

autodecoder_arm_monolithic_57:
  if ((instruction & (1u << 6)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_56:
  if ((instruction & (1u << 20)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_55:
  if ((instruction & (1u << 22)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  return isbInstruction;


autodecoder_arm_monolithic_61:
  if ((instruction & (1u << 6)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_60:
  if ((instruction & (1u << 20)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_59:
  if ((instruction & (1u << 22)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  return dsbInstruction;


autodecoder_arm_monolithic_22:
  if ((instruction & (1u << 20)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  return pldInstruction;


autodecoder_arm_monolithic_27:
  if (instruction & (1u << 21))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_26:
  if ((instruction & (1u << 20)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_25:
  if ((instruction & (1u << 22)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  return pliInstruction;


autodecoder_arm_monolithic_611:
  if (instruction & (1u << 26))
  {
    goto autodecoder_arm_monolithic_288;
  }

autodecoder_arm_monolithic_610:
  if (instruction & (1u << 25))
  {
    goto autodecoder_arm_monolithic_380;
  }

autodecoder_arm_monolithic_609:
  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_608;
  }

autodecoder_arm_monolithic_521:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_520;
  }

autodecoder_arm_monolithic_488:
  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_430;
  }

autodecoder_arm_monolithic_487:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_445;
  }

autodecoder_arm_monolithic_486:
  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_485;
  }

autodecoder_arm_monolithic_469:
  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_arm_monolithic_466;
  }

autodecoder_arm_monolithic_468:
  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_arm_monolithic_466;
  }

autodecoder_arm_monolithic_467:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_466;
  }

autodecoder_arm_monolithic_465:
  if ((instruction & (1u << 21)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_464:
  if ((instruction & (1u << 16)) == 0)
  {
    goto autodecoder_arm_monolithic_460;
  }

autodecoder_arm_monolithic_463:
  if ((instruction & (1u << 19)) == 0)
  {
    goto autodecoder_arm_monolithic_460;
  }

autodecoder_arm_monolithic_462:
  if ((instruction & (1u << 18)) == 0)
  {
    goto autodecoder_arm_monolithic_460;
  }

autodecoder_arm_monolithic_461:
  if ((instruction & (1u << 17)) == 0)
  {
    goto autodecoder_arm_monolithic_460;
  }

autodecoder_arm_monolithic_458:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_457;
  }

autodecoder_arm_monolithic_453:
  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_449;
  }
  goto autodecoder_arm_monolithic_452;

autodecoder_arm_monolithic_743:
  if ((instruction & (1u << 27)) == 0)
  {
    goto autodecoder_arm_monolithic_742;
  }

autodecoder_arm_monolithic_696:
  if (instruction & (1u << 12))
  {
    goto autodecoder_arm_monolithic_661;
  }

autodecoder_arm_monolithic_695:
  if (instruction & (1u << 13))
  {
    goto autodecoder_arm_monolithic_661;
  }

autodecoder_arm_monolithic_694:
  if ((instruction & (1u << 14)) == 0)
  {
    goto autodecoder_arm_monolithic_693;
  }

autodecoder_arm_monolithic_661:
  if ((instruction & (1u << 28)) == 0)
  {
    goto autodecoder_arm_monolithic_660;
  }

autodecoder_arm_monolithic_3:
  if (instruction & (1u << 26))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_2:
  if (instruction & (1u << 25))
  {
    return armBlxImmediateInstruction;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");

autodecoder_arm_monolithic_693:
  if ((instruction & (1u << 28)) == 0)
  {
    goto autodecoder_arm_monolithic_660;
  }

autodecoder_arm_monolithic_692:
  if (instruction & (1u << 26))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_691:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_690;
  }
  return armBlxImmediateInstruction;


autodecoder_arm_monolithic_690:
  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_689;
  }

autodecoder_arm_monolithic_675:
  if (instruction & (1u << 7))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_674:
  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_673;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");

autodecoder_arm_monolithic_689:
  if (instruction & (1u << 7))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_688:
  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_687;
  }

autodecoder_arm_monolithic_673:
  if (instruction & (1u << 11))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_672:
  if ((instruction & (1u << 10)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_671:
  if (instruction & (1u << 9))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_670:
  if ((instruction & (1u << 16)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_669:
  if ((instruction & (1u << 19)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_668:
  if ((instruction & (1u << 18)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_667:
  if (instruction & (1u << 17))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_666:
  if (instruction & (1u << 5))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_665:
  if (instruction & (1u << 6))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_664:
  if (instruction & (1u << 20))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_663:
  if ((instruction & (1u << 22)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  return srsInstruction;


autodecoder_arm_monolithic_687:
  if ((instruction & (1u << 11)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_686:
  if (instruction & (1u << 10))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_685:
  if ((instruction & (1u << 9)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_684:
  if (instruction & (1u << 5))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_683:
  if (instruction & (1u << 6))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_682:
  if ((instruction & (1u << 20)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_681:
  if (instruction & (1u << 3))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_680:
  if (instruction & (1u << 1))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_679:
  if (instruction & (1u << 2))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_678:
  if (instruction & (1u << 0))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_677:
  if (instruction & (1u << 22))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  return rfeInstruction;


autodecoder_arm_monolithic_742:
  if (instruction & (1u << 12))
  {
    goto autodecoder_arm_monolithic_652;
  }

autodecoder_arm_monolithic_741:
  if (instruction & (1u << 13))
  {
    goto autodecoder_arm_monolithic_652;
  }

autodecoder_arm_monolithic_740:
  if ((instruction & (1u << 14)) == 0)
  {
    goto autodecoder_arm_monolithic_739;
  }

autodecoder_arm_monolithic_652:
  if (instruction & (1u << 28))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_651:
  if (instruction & (1u << 26))
  {
    goto autodecoder_arm_monolithic_627;
  }

autodecoder_arm_monolithic_650:
  if (instruction & (1u << 25))
  {
    goto autodecoder_arm_monolithic_634;
  }

autodecoder_arm_monolithic_649:
  if (instruction & (1u << 4))
  {
    goto autodecoder_arm_monolithic_639;
  }
  goto autodecoder_arm_monolithic_648;

autodecoder_arm_monolithic_739:
  if ((instruction & (1u << 28)) == 0)
  {
    goto autodecoder_arm_monolithic_738;
  }

autodecoder_arm_monolithic_717:
  if (instruction & (1u << 26))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_716:
  if (instruction & (1u << 25))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_715:
  if ((instruction & (1u << 24)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_714:
  if (instruction & (1u << 23))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_713:
  if (instruction & (1u << 11))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_712:
  if (instruction & (1u << 10))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_711:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_710;
  }

autodecoder_arm_monolithic_704:
  if (instruction & (1u << 21))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_703:
  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_monolithic_702;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");

autodecoder_arm_monolithic_710:
  if (instruction & (1u << 21))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_709:
  if ((instruction & (1u << 16)) == 0)
  {
    goto autodecoder_arm_monolithic_708;
  }

autodecoder_arm_monolithic_702:
  if (instruction & (1u << 19))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_701:
  if (instruction & (1u << 18))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_700:
  if (instruction & (1u << 17))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_699:
  if (instruction & (1u << 20))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_698:
  if (instruction & (1u << 22))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  return setendInstruction;


autodecoder_arm_monolithic_708:
  if (instruction & (1u << 5))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_707:
  if (instruction & (1u << 20))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_706:
  if (instruction & (1u << 22))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  return cpsInstruction;


autodecoder_arm_monolithic_738:
  if (instruction & (1u << 26))
  {
    goto autodecoder_arm_monolithic_627;
  }

autodecoder_arm_monolithic_737:
  if (instruction & (1u << 25))
  {
    goto autodecoder_arm_monolithic_634;
  }

autodecoder_arm_monolithic_736:
  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_735;
  }

autodecoder_arm_monolithic_639:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_638;
  }

autodecoder_arm_monolithic_637:
  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_430;
  }

autodecoder_arm_monolithic_636:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_632;
  }

autodecoder_arm_monolithic_635:
  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_466;
  }

autodecoder_arm_monolithic_485:
  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_466;
  }

autodecoder_arm_monolithic_484:
  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_466;
  }

autodecoder_arm_monolithic_483:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_482;
  }

autodecoder_arm_monolithic_466:
  if ((instruction & (1u << 21)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_460:
  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_459;
  }
  return 0;

autodecoder_arm_monolithic_482:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_481;
  }

autodecoder_arm_monolithic_475:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_474;
  }

autodecoder_arm_monolithic_459:
  if ((instruction & (1u << 6)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_449:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_448:
  if (instruction & (1u << 22))
  {
    return smcInstruction;
  }
  return bkptInstruction;


autodecoder_arm_monolithic_790:
  if ((instruction & (1u << 15)) == 0)
  {
    goto autodecoder_arm_monolithic_789;
  }

autodecoder_arm_monolithic_782:
  if ((instruction & (1u << 27)) == 0)
  {
    goto autodecoder_arm_monolithic_781;
  }

autodecoder_arm_monolithic_19:
  if (instruction & (1u << 26))
  {
    goto autodecoder_arm_monolithic_11;
  }

autodecoder_arm_monolithic_18:
  if (instruction & (1u << 25))
  {
    return armBInstruction;
  }

autodecoder_arm_monolithic_17:
  if (instruction & (1u << 20))
  {
    return armLdmInstruction;
  }
  goto autodecoder_arm_monolithic_16;

autodecoder_arm_monolithic_781:
  if ((instruction & (1u << 12)) == 0)
  {
    goto autodecoder_arm_monolithic_778;
  }

autodecoder_arm_monolithic_780:
  if ((instruction & (1u << 13)) == 0)
  {
    goto autodecoder_arm_monolithic_778;
  }

autodecoder_arm_monolithic_779:
  if ((instruction & (1u << 14)) == 0)
  {
    goto autodecoder_arm_monolithic_778;
  }

autodecoder_arm_monolithic_771:
  if ((instruction & (1u << 26)) == 0)
  {
    goto autodecoder_arm_monolithic_770;
  }

autodecoder_arm_monolithic_288:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_286;
  }

autodecoder_arm_monolithic_287:
  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_286;
  }

autodecoder_arm_monolithic_284:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_283;
  }

autodecoder_arm_monolithic_103:
  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_89;
  }

autodecoder_arm_monolithic_102:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_83;
  }

autodecoder_arm_monolithic_101:
  if (instruction & (1u << 21))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_100:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_99;
  }

autodecoder_arm_monolithic_93:
  if (instruction & (1u << 20))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_92:
  if (instruction & (1u << 22))
  {
    return smlsldInstruction;
  }
  return smusdInstruction;


autodecoder_arm_monolithic_99:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_98;
  }

autodecoder_arm_monolithic_95:
  if ((instruction & (1u << 22)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  return smmulInstruction;


autodecoder_arm_monolithic_98:
  if (instruction & (1u << 22))
  {
    return smlaldInstruction;
  }
  return smuadInstruction;


autodecoder_arm_monolithic_286:
  if ((instruction & (1u << 20)) == 0)
  {
    return 0;
  }
  return armLdrInstruction;


autodecoder_arm_monolithic_770:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_769;
  }

autodecoder_arm_monolithic_380:
  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_379;
  }

autodecoder_arm_monolithic_336:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_335;
  }

autodecoder_arm_monolithic_320:
  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_319;
  }

autodecoder_arm_monolithic_318:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_300;
  }

autodecoder_arm_monolithic_317:
  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_303;
  }

autodecoder_arm_monolithic_316:
  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_303;
  }

autodecoder_arm_monolithic_315:
  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_303;
  }

autodecoder_arm_monolithic_314:
  if (instruction & (1u << 9))
  {
    goto autodecoder_arm_monolithic_303;
  }

autodecoder_arm_monolithic_313:
  if ((instruction & (1u << 21)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_312:
  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_monolithic_302;
  }

autodecoder_arm_monolithic_311:
  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_monolithic_302;
  }

autodecoder_arm_monolithic_310:
  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_monolithic_302;
  }

autodecoder_arm_monolithic_309:
  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_monolithic_302;
  }

autodecoder_arm_monolithic_308:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_302;
  }

autodecoder_arm_monolithic_307:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_302;
  }

autodecoder_arm_monolithic_306:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_305:
  if (instruction & (1u << 22))
  {
    return msrInstruction;
  }
  return dbgInstruction;


autodecoder_arm_monolithic_379:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_335;
  }

autodecoder_arm_monolithic_378:
  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_377;
  }

autodecoder_arm_monolithic_319:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_300;
  }

autodecoder_arm_monolithic_303:
  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_monolithic_302;
  }
  return 0;

autodecoder_arm_monolithic_377:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_376;
  }

autodecoder_arm_monolithic_300:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_299;
  }

autodecoder_arm_monolithic_296:
  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_monolithic_290;
  }

autodecoder_arm_monolithic_295:
  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_monolithic_290;
  }

autodecoder_arm_monolithic_294:
  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_monolithic_290;
  }

autodecoder_arm_monolithic_293:
  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_monolithic_290;
  }
  goto autodecoder_arm_monolithic_292;

autodecoder_arm_monolithic_376:
  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_349;
  }

autodecoder_arm_monolithic_375:
  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_349;
  }

autodecoder_arm_monolithic_374:
  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_349;
  }

autodecoder_arm_monolithic_373:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_372;
  }

autodecoder_arm_monolithic_349:
  if ((instruction & (1u << 21)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_348:
  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_monolithic_302;
  }

autodecoder_arm_monolithic_347:
  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_monolithic_302;
  }

autodecoder_arm_monolithic_346:
  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_monolithic_302;
  }

autodecoder_arm_monolithic_345:
  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_monolithic_302;
  }

autodecoder_arm_monolithic_344:
  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_302;
  }

autodecoder_arm_monolithic_343:
  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_302;
  }

autodecoder_arm_monolithic_342:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_341:
  if (instruction & (1u << 3))
  {
    return msrInstruction;
  }

autodecoder_arm_monolithic_340:
  if (instruction & (1u << 1))
  {
    return msrInstruction;
  }

autodecoder_arm_monolithic_339:
  if (instruction & (1u << 2))
  {
    return msrInstruction;
  }

autodecoder_arm_monolithic_338:
  if (instruction & (1u << 0))
  {
    return msrInstruction;
  }
  goto autodecoder_arm_monolithic_337;

autodecoder_arm_monolithic_372:
  if ((instruction & (1u << 21)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_371:
  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_monolithic_302;
  }

autodecoder_arm_monolithic_370:
  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_monolithic_302;
  }

autodecoder_arm_monolithic_369:
  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_monolithic_302;
  }

autodecoder_arm_monolithic_368:
  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_monolithic_302;
  }

autodecoder_arm_monolithic_367:
  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_302;
  }

autodecoder_arm_monolithic_366:
  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_302;
  }

autodecoder_arm_monolithic_365:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_364:
  if (instruction & (1u << 3))
  {
    return msrInstruction;
  }

autodecoder_arm_monolithic_363:
  if ((instruction & (1u << 1)) == 0)
  {
    goto autodecoder_arm_monolithic_362;
  }

autodecoder_arm_monolithic_355:
  if (instruction & (1u << 2))
  {
    return msrInstruction;
  }

autodecoder_arm_monolithic_354:
  if ((instruction & (1u << 0)) == 0)
  {
    goto autodecoder_arm_monolithic_353;
  }

autodecoder_arm_monolithic_351:
  if (instruction & (1u << 22))
  {
    return msrInstruction;
  }
  return wfiInstruction;


autodecoder_arm_monolithic_353:
  if (instruction & (1u << 22))
  {
    return msrInstruction;
  }
  return wfeInstruction;


autodecoder_arm_monolithic_362:
  if ((instruction & (1u << 2)) == 0)
  {
    goto autodecoder_arm_monolithic_361;
  }

autodecoder_arm_monolithic_358:
  if (instruction & (1u << 0))
  {
    return msrInstruction;
  }

autodecoder_arm_monolithic_357:
  if (instruction & (1u << 22))
  {
    return msrInstruction;
  }
  return sevInstruction;


autodecoder_arm_monolithic_361:
  if ((instruction & (1u << 0)) == 0)
  {
    goto autodecoder_arm_monolithic_337;
  }

autodecoder_arm_monolithic_360:
  if (instruction & (1u << 22))
  {
    return msrInstruction;
  }
  return yieldInstruction;


autodecoder_arm_monolithic_337:
  if (instruction & (1u << 22))
  {
    return msrInstruction;
  }
  return 0;

autodecoder_arm_monolithic_769:
  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_608;
  }

autodecoder_arm_monolithic_768:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_520;
  }

autodecoder_arm_monolithic_767:
  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_430;
  }

autodecoder_arm_monolithic_766:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_765;
  }

autodecoder_arm_monolithic_445:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_299;
  }

autodecoder_arm_monolithic_444:
  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_monolithic_290;
  }

autodecoder_arm_monolithic_443:
  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_monolithic_290;
  }

autodecoder_arm_monolithic_442:
  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_monolithic_290;
  }

autodecoder_arm_monolithic_441:
  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_monolithic_290;
  }

autodecoder_arm_monolithic_440:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_439;
  }

autodecoder_arm_monolithic_434:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_433;
  }

autodecoder_arm_monolithic_431:
  if (instruction & (1u << 22))
  {
    return mvnInstruction;
  }
  return 0;

autodecoder_arm_monolithic_765:
  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_764;
  }

autodecoder_arm_monolithic_759:
  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_arm_monolithic_756;
  }

autodecoder_arm_monolithic_758:
  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_arm_monolithic_756;
  }

autodecoder_arm_monolithic_757:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_756;
  }

autodecoder_arm_monolithic_755:
  if ((instruction & (1u << 21)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_754:
  if ((instruction & (1u << 16)) == 0)
  {
    goto autodecoder_arm_monolithic_750;
  }

autodecoder_arm_monolithic_753:
  if ((instruction & (1u << 19)) == 0)
  {
    goto autodecoder_arm_monolithic_750;
  }

autodecoder_arm_monolithic_752:
  if ((instruction & (1u << 18)) == 0)
  {
    goto autodecoder_arm_monolithic_750;
  }

autodecoder_arm_monolithic_751:
  if ((instruction & (1u << 17)) == 0)
  {
    goto autodecoder_arm_monolithic_750;
  }

autodecoder_arm_monolithic_748:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_457;
  }

autodecoder_arm_monolithic_747:
  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_746;
  }

autodecoder_arm_monolithic_452:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_451:
  if (instruction & (1u << 22))
  {
    return 0;
  }
  return armBlxRegisterInstruction;


autodecoder_arm_monolithic_457:
  if (instruction & (1u << 6))
  {
    return 0;
  }

autodecoder_arm_monolithic_456:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_455:
  if (instruction & (1u << 22))
  {
    return 0;
  }
  return armBxInstruction;


autodecoder_arm_monolithic_520:
  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_519;
  }
  goto autodecoder_arm_monolithic_335;

autodecoder_arm_monolithic_608:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_335;
  }

autodecoder_arm_monolithic_607:
  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_606;
  }

autodecoder_arm_monolithic_559:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_530;
  }
  goto autodecoder_arm_monolithic_558;

autodecoder_arm_monolithic_606:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_605;
  }

autodecoder_arm_monolithic_573:
  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_530;
  }

autodecoder_arm_monolithic_572:
  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_530;
  }

autodecoder_arm_monolithic_571:
  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_530;
  }

autodecoder_arm_monolithic_570:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_569;
  }

autodecoder_arm_monolithic_530:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_299;
  }

autodecoder_arm_monolithic_529:
  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_monolithic_290;
  }

autodecoder_arm_monolithic_528:
  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_monolithic_290;
  }

autodecoder_arm_monolithic_527:
  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_monolithic_290;
  }

autodecoder_arm_monolithic_526:
  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_monolithic_290;
  }

autodecoder_arm_monolithic_525:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_439;
  }

autodecoder_arm_monolithic_524:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_433;
  }

autodecoder_arm_monolithic_523:
  if (instruction & (1u << 22))
  {
    return mvnInstruction;
  }
  return rorInstruction;


autodecoder_arm_monolithic_439:
  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_436;
  }

autodecoder_arm_monolithic_438:
  if (instruction & (1u << 22))
  {
    return mvnInstruction;
  }
  return lslInstruction;


autodecoder_arm_monolithic_569:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_299;
  }

autodecoder_arm_monolithic_568:
  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_monolithic_290;
  }

autodecoder_arm_monolithic_567:
  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_monolithic_290;
  }

autodecoder_arm_monolithic_566:
  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_monolithic_290;
  }

autodecoder_arm_monolithic_565:
  if ((instruction & (1u << 17)) == 0)
  {
    goto autodecoder_arm_monolithic_564;
  }

autodecoder_arm_monolithic_290:
  if (instruction & (1u << 22))
  {
    return mvnInstruction;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");

autodecoder_arm_monolithic_564:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_563;
  }

autodecoder_arm_monolithic_562:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_433;
  }

autodecoder_arm_monolithic_561:
  if (instruction & (1u << 22))
  {
    return mvnInstruction;
  }
  return rrxInstruction;


autodecoder_arm_monolithic_433:
  if (instruction & (1u << 22))
  {
    return mvnInstruction;
  }
  return lsrInstruction;


autodecoder_arm_monolithic_563:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_292;
  }

autodecoder_arm_monolithic_436:
  if (instruction & (1u << 22))
  {
    return mvnInstruction;
  }
  return asrInstruction;


autodecoder_arm_monolithic_292:
  if ((instruction & (1u << 22)) == 0)
  {
    return movInstruction;
  }
  return mvnInstruction;



autodecoder_arm_monolithic_299:
  if ((instruction & (1u << 22)) == 0)
  {
    return orrInstruction;
  }
  return bicInstruction;



autodecoder_arm_monolithic_605:
  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_604;
  }

autodecoder_arm_monolithic_586:
  if ((instruction & (1u << 11)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_585:
  if ((instruction & (1u << 10)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_584:
  if ((instruction & (1u << 9)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_583:
  if ((instruction & (1u << 21)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_582:
  if ((instruction & (1u << 16)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_581:
  if ((instruction & (1u << 19)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_580:
  if ((instruction & (1u << 18)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_579:
  if ((instruction & (1u << 17)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_578:
  if ((instruction & (1u << 5)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_577:
  if (instruction & (1u << 6))
  {
    return 0;
  }

autodecoder_arm_monolithic_576:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_575:
  if (instruction & (1u << 22))
  {
    return 0;
  }
  return armBxjInstruction;


autodecoder_arm_monolithic_604:
  if (instruction & (1u << 11))
  {
    return 0;
  }

autodecoder_arm_monolithic_603:
  if (instruction & (1u << 10))
  {
    return 0;
  }

autodecoder_arm_monolithic_602:
  if (instruction & (1u << 9))
  {
    return 0;
  }

autodecoder_arm_monolithic_601:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_600;
  }

autodecoder_arm_monolithic_588:
  if (instruction & (1u << 5))
  {
    return 0;
  }

autodecoder_arm_monolithic_587:
  if (instruction & (1u << 6))
  {
    return 0;
  }

autodecoder_arm_monolithic_302:
  if (instruction & (1u << 20))
  {
    return 0;
  }
  return msrInstruction;


autodecoder_arm_monolithic_335:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_334;
  }

autodecoder_arm_monolithic_327:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_326;
  }

autodecoder_arm_monolithic_323:
  if ((instruction & (1u << 22)) == 0)
  {
    return adcInstruction;
  }
  return rscInstruction;



autodecoder_arm_monolithic_326:
  if ((instruction & (1u << 22)) == 0)
  {
    return addInstruction;
  }
  return sbcInstruction;



autodecoder_arm_monolithic_334:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_333;
  }

autodecoder_arm_monolithic_330:
  if ((instruction & (1u << 22)) == 0)
  {
    return eorInstruction;
  }
  return rsbInstruction;



autodecoder_arm_monolithic_333:
  if ((instruction & (1u << 22)) == 0)
  {
    return andInstruction;
  }
  return subInstruction;



autodecoder_arm_monolithic_789:
  if ((instruction & (1u << 27)) == 0)
  {
    goto autodecoder_arm_monolithic_788;
  }

autodecoder_arm_monolithic_660:
  if ((instruction & (1u << 26)) == 0)
  {
    goto autodecoder_arm_monolithic_659;
  }

autodecoder_arm_monolithic_11:
  if ((instruction & (1u << 25)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_10:
  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_9;
  }

autodecoder_arm_monolithic_8:
  if (instruction & (1u << 24))
  {
    return svcInstruction;
  }

autodecoder_arm_monolithic_7:
  if ((instruction & (1u << 20)) == 0)
  {
    return armMcrInstruction;
  }
  return armMrcInstruction;



autodecoder_arm_monolithic_9:
  if ((instruction & (1u << 24)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  return svcInstruction;


autodecoder_arm_monolithic_659:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_658;
  }
  return armBInstruction;


autodecoder_arm_monolithic_658:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_16;
  }

autodecoder_arm_monolithic_657:
  if ((instruction & (1u << 22)) == 0)
  {
    return 0;
  }
  return armLdmInstruction;


autodecoder_arm_monolithic_16:
  if ((instruction & (1u << 22)) == 0)
  {
    return 0;
  }
  return armStmInstruction;


autodecoder_arm_monolithic_788:
  if (instruction & (1u << 12))
  {
    goto autodecoder_arm_monolithic_778;
  }

autodecoder_arm_monolithic_787:
  if (instruction & (1u << 13))
  {
    goto autodecoder_arm_monolithic_778;
  }

autodecoder_arm_monolithic_786:
  if ((instruction & (1u << 14)) == 0)
  {
    goto autodecoder_arm_monolithic_785;
  }

autodecoder_arm_monolithic_778:
  if (instruction & (1u << 26))
  {
    goto autodecoder_arm_monolithic_627;
  }

autodecoder_arm_monolithic_777:
  if (instruction & (1u << 25))
  {
    goto autodecoder_arm_monolithic_634;
  }

autodecoder_arm_monolithic_776:
  if (instruction & (1u << 4))
  {
    goto autodecoder_arm_monolithic_775;
  }

autodecoder_arm_monolithic_648:
  if ((instruction & (1u << 24)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_647:
  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_646;
  }

autodecoder_arm_monolithic_640:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_632;
  }

autodecoder_arm_monolithic_558:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_557;
  }

autodecoder_arm_monolithic_538:
  if (instruction & (1u << 5))
  {
    return 0;
  }

autodecoder_arm_monolithic_537:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_536;
  }

autodecoder_arm_monolithic_533:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_532:
  if (instruction & (1u << 22))
  {
    return 0;
  }
  return smlawtInstruction;

autodecoder_arm_monolithic_785:
  if ((instruction & (1u << 26)) == 0)
  {
    goto autodecoder_arm_monolithic_784;
  }

autodecoder_arm_monolithic_627:
  if ((instruction & (1u << 25)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_626:
  if ((instruction & (1u << 4)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_625:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_283;
  }

autodecoder_arm_monolithic_624:
  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_623;
  }

autodecoder_arm_monolithic_89:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_83;
  }

autodecoder_arm_monolithic_88:
  if (instruction & (1u << 21))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_87:
  if ((instruction & (1u << 6)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_86:
  if ((instruction & (1u << 20)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_85:
  if ((instruction & (1u << 22)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  return smmlsInstruction;


autodecoder_arm_monolithic_623:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_622;
  }

autodecoder_arm_monolithic_83:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_82;
  }

autodecoder_arm_monolithic_79:
  if (instruction & (1u << 5))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_78:
  if (instruction & (1u << 6))
  {
    return 0;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");

autodecoder_arm_monolithic_82:
  if (instruction & (1u << 5))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_81:
  if (instruction & (1u << 6))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  goto autodecoder_arm_monolithic_80;

autodecoder_arm_monolithic_622:
  if (instruction & (1u << 21))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_621:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_620;
  }

autodecoder_arm_monolithic_615:
  if (instruction & (1u << 20))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_614:
  if ((instruction & (1u << 22)) == 0)
  {
    return smlsdInstruction;
  }
  return smlsldInstruction;



autodecoder_arm_monolithic_620:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_619;
  }

autodecoder_arm_monolithic_617:
  if ((instruction & (1u << 22)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  return smmlaInstruction;


autodecoder_arm_monolithic_619:
  if ((instruction & (1u << 22)) == 0)
  {
    return smladInstruction;
  }
  return smlaldInstruction;



autodecoder_arm_monolithic_283:
  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_282;
  }

autodecoder_arm_monolithic_170:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_169;
  }

autodecoder_arm_monolithic_136:
  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_132;
  }

autodecoder_arm_monolithic_135:
  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_arm_monolithic_132;
  }

autodecoder_arm_monolithic_134:
  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_arm_monolithic_132;
  }

autodecoder_arm_monolithic_133:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_132;
  }

autodecoder_arm_monolithic_130:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_129;
  }

autodecoder_arm_monolithic_117:
  if ((instruction & (1u << 16)) == 0)
  {
    goto autodecoder_arm_monolithic_113;
  }

autodecoder_arm_monolithic_116:
  if ((instruction & (1u << 19)) == 0)
  {
    goto autodecoder_arm_monolithic_113;
  }

autodecoder_arm_monolithic_115:
  if ((instruction & (1u << 18)) == 0)
  {
    goto autodecoder_arm_monolithic_113;
  }

autodecoder_arm_monolithic_114:
  if ((instruction & (1u << 17)) == 0)
  {
    goto autodecoder_arm_monolithic_113;
  }

autodecoder_arm_monolithic_112:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_111;
  }

autodecoder_arm_monolithic_108:
  if (instruction & (1u << 6))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_107:
  if ((instruction & (1u << 20)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_106:
  if ((instruction & (1u << 22)) == 0)
  {
    return rev16Instruction;
  }
  return revshInstruction;



autodecoder_arm_monolithic_129:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_128;
  }

autodecoder_arm_monolithic_121:
  if (instruction & (1u << 6))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_120:
  if (instruction & (1u << 20))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_119:
  if (instruction & (1u << 22))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  return selInstruction;


autodecoder_arm_monolithic_169:
  if ((instruction & (1u << 8)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_168:
  if ((instruction & (1u << 11)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_167:
  if ((instruction & (1u << 10)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_166:
  if ((instruction & (1u << 9)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_165:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_164;
  }

autodecoder_arm_monolithic_153:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_152;
  }

autodecoder_arm_monolithic_144:
  if ((instruction & (1u << 6)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_143:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_142;
  }

autodecoder_arm_monolithic_139:
  if ((instruction & (1u << 22)) == 0)
  {
    return shsub8Instruction;
  }
  return uhsub8Instruction;



autodecoder_arm_monolithic_142:
  if ((instruction & (1u << 22)) == 0)
  {
    return qsub8Instruction;
  }
  return uqsub8Instruction;



autodecoder_arm_monolithic_152:
  if (instruction & (1u << 6))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_151:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_150;
  }

autodecoder_arm_monolithic_147:
  if ((instruction & (1u << 22)) == 0)
  {
    return shadd8Instruction;
  }
  return uhadd8Instruction;



autodecoder_arm_monolithic_150:
  if ((instruction & (1u << 22)) == 0)
  {
    return qadd8Instruction;
  }
  return uqadd8Instruction;



autodecoder_arm_monolithic_164:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_163;
  }

autodecoder_arm_monolithic_158:
  if ((instruction & (1u << 6)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_157:
  if ((instruction & (1u << 20)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_156:
  if ((instruction & (1u << 22)) == 0)
  {
    return ssub8Instruction;
  }
  return usub8Instruction;



autodecoder_arm_monolithic_163:
  if (instruction & (1u << 6))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_162:
  if ((instruction & (1u << 20)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_161:
  if ((instruction & (1u << 22)) == 0)
  {
    return sadd8Instruction;
  }
  return uadd8Instruction;



autodecoder_arm_monolithic_282:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_281;
  }

autodecoder_arm_monolithic_226:
  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_225;
  }

autodecoder_arm_monolithic_190:
  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_arm_monolithic_132;
  }

autodecoder_arm_monolithic_189:
  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_arm_monolithic_132;
  }

autodecoder_arm_monolithic_188:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_132;
  }

autodecoder_arm_monolithic_187:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_131;
  }

autodecoder_arm_monolithic_186:
  if ((instruction & (1u << 16)) == 0)
  {
    goto autodecoder_arm_monolithic_182;
  }

autodecoder_arm_monolithic_185:
  if ((instruction & (1u << 19)) == 0)
  {
    goto autodecoder_arm_monolithic_182;
  }

autodecoder_arm_monolithic_184:
  if ((instruction & (1u << 18)) == 0)
  {
    goto autodecoder_arm_monolithic_182;
  }

autodecoder_arm_monolithic_183:
  if ((instruction & (1u << 17)) == 0)
  {
    goto autodecoder_arm_monolithic_182;
  }

autodecoder_arm_monolithic_179:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_111;
  }

autodecoder_arm_monolithic_178:
  if (instruction & (1u << 6))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_177:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_176;
  }

autodecoder_arm_monolithic_173:
  if ((instruction & (1u << 22)) == 0)
  {
    return revInstruction;
  }
  return rbitInstruction;



autodecoder_arm_monolithic_182:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_111;
  }

autodecoder_arm_monolithic_181:
  if (instruction & (1u << 6))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_180:
  if (instruction & (1u << 20))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_176:
  if ((instruction & (1u << 22)) == 0)
  {
    return ssat16Instruction;
  }
  return usat16Instruction;



autodecoder_arm_monolithic_225:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_224;
  }

autodecoder_arm_monolithic_132:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_131;
  }

autodecoder_arm_monolithic_113:
  if (instruction & (1u << 5))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  goto autodecoder_arm_monolithic_111;

autodecoder_arm_monolithic_131:
  if (instruction & (1u << 5))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  goto autodecoder_arm_monolithic_128;

autodecoder_arm_monolithic_224:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_223;
  }

autodecoder_arm_monolithic_208:
  if ((instruction & (1u << 16)) == 0)
  {
    goto autodecoder_arm_monolithic_204;
  }

autodecoder_arm_monolithic_207:
  if ((instruction & (1u << 19)) == 0)
  {
    goto autodecoder_arm_monolithic_204;
  }

autodecoder_arm_monolithic_206:
  if ((instruction & (1u << 18)) == 0)
  {
    goto autodecoder_arm_monolithic_204;
  }

autodecoder_arm_monolithic_205:
  if ((instruction & (1u << 17)) == 0)
  {
    goto autodecoder_arm_monolithic_204;
  }

autodecoder_arm_monolithic_195:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_111;
  }

autodecoder_arm_monolithic_194:
  if ((instruction & (1u << 6)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_193:
  if ((instruction & (1u << 20)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_192:
  if (instruction & (1u << 22))
  {
    return 0;
  }
  return sxthInstruction;


autodecoder_arm_monolithic_204:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_111;
  }

autodecoder_arm_monolithic_203:
  if ((instruction & (1u << 6)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_202:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_201;
  }

autodecoder_arm_monolithic_198:
  if ((instruction & (1u << 22)) == 0)
  {
    return sxtahInstruction;
  }
  return uxtahInstruction;



autodecoder_arm_monolithic_201:
  if ((instruction & (1u << 22)) == 0)
  {
    return sxtabInstruction;
  }
  return uxtabInstruction;



autodecoder_arm_monolithic_111:
  if ((instruction & (1u << 22)) == 0)
  {
    return ssatInstruction;
  }
  return usatInstruction;



autodecoder_arm_monolithic_223:
  if ((instruction & (1u << 16)) == 0)
  {
    goto autodecoder_arm_monolithic_219;
  }

autodecoder_arm_monolithic_222:
  if ((instruction & (1u << 19)) == 0)
  {
    goto autodecoder_arm_monolithic_219;
  }

autodecoder_arm_monolithic_221:
  if ((instruction & (1u << 18)) == 0)
  {
    goto autodecoder_arm_monolithic_219;
  }

autodecoder_arm_monolithic_220:
  if ((instruction & (1u << 17)) == 0)
  {
    goto autodecoder_arm_monolithic_219;
  }

autodecoder_arm_monolithic_213:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_128;
  }

autodecoder_arm_monolithic_212:
  if ((instruction & (1u << 6)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_211:
  if (instruction & (1u << 20))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_210:
  if (instruction & (1u << 22))
  {
    return 0;
  }
  return sxtb16Instruction;


autodecoder_arm_monolithic_219:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_128;
  }

autodecoder_arm_monolithic_218:
  if ((instruction & (1u << 6)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_217:
  if (instruction & (1u << 20))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_216:
  if ((instruction & (1u << 22)) == 0)
  {
    return sxtab16Instruction;
  }
  return uxtab16Instruction;



autodecoder_arm_monolithic_128:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_127;
  }

autodecoder_arm_monolithic_124:
  if (instruction & (1u << 20))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_123:
  if (instruction & (1u << 22))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  return pkhtbInstruction;


autodecoder_arm_monolithic_127:
  if (instruction & (1u << 20))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_126:
  if (instruction & (1u << 22))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  return pkhbtInstruction;


autodecoder_arm_monolithic_281:
  if ((instruction & (1u << 8)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_280:
  if ((instruction & (1u << 11)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_279:
  if ((instruction & (1u << 10)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_278:
  if ((instruction & (1u << 9)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_277:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_276;
  }

autodecoder_arm_monolithic_257:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_256;
  }

autodecoder_arm_monolithic_241:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_240;
  }

autodecoder_arm_monolithic_233:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_232;
  }

autodecoder_arm_monolithic_229:
  if ((instruction & (1u << 22)) == 0)
  {
    return shsub16Instruction;
  }
  return uhsub16Instruction;



autodecoder_arm_monolithic_232:
  if ((instruction & (1u << 22)) == 0)
  {
    return qsub16Instruction;
  }
  return uqsub16Instruction;



autodecoder_arm_monolithic_240:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_239;
  }

autodecoder_arm_monolithic_236:
  if ((instruction & (1u << 22)) == 0)
  {
    return shaddsubxInstruction;
  }
  return uhaddsubxInstruction;



autodecoder_arm_monolithic_239:
  if ((instruction & (1u << 22)) == 0)
  {
    return qaddsubxInstruction;
  }
  return uqaddsubxInstruction;



autodecoder_arm_monolithic_256:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_255;
  }

autodecoder_arm_monolithic_248:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_247;
  }

autodecoder_arm_monolithic_244:
  if ((instruction & (1u << 22)) == 0)
  {
    return shsubaddxInstruction;
  }
  return uhsubaddxInstruction;



autodecoder_arm_monolithic_247:
  if ((instruction & (1u << 22)) == 0)
  {
    return qsubaddxInstruction;
  }
  return uqsubaddxInstruction;



autodecoder_arm_monolithic_255:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_254;
  }

autodecoder_arm_monolithic_251:
  if ((instruction & (1u << 22)) == 0)
  {
    return shadd16Instruction;
  }
  return uhadd16Instruction;



autodecoder_arm_monolithic_254:
  if ((instruction & (1u << 22)) == 0)
  {
    return qadd16Instruction;
  }
  return uqadd16Instruction;



autodecoder_arm_monolithic_276:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_275;
  }

autodecoder_arm_monolithic_266:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_265;
  }

autodecoder_arm_monolithic_261:
  if ((instruction & (1u << 20)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_260:
  if ((instruction & (1u << 22)) == 0)
  {
    return ssub16Instruction;
  }
  return usub16Instruction;



autodecoder_arm_monolithic_265:
  if ((instruction & (1u << 20)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_264:
  if ((instruction & (1u << 22)) == 0)
  {
    return saddsubxInstruction;
  }
  return uaddsubxInstruction;



autodecoder_arm_monolithic_275:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_274;
  }

autodecoder_arm_monolithic_270:
  if ((instruction & (1u << 20)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_269:
  if ((instruction & (1u << 22)) == 0)
  {
    return ssubaddxInstruction;
  }
  return usubaddxInstruction;



autodecoder_arm_monolithic_274:
  if ((instruction & (1u << 20)) == 0)
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }

autodecoder_arm_monolithic_273:
  if ((instruction & (1u << 22)) == 0)
  {
    return sadd16Instruction;
  }
  return uadd16Instruction;



autodecoder_arm_monolithic_784:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_783;
  }

autodecoder_arm_monolithic_634:
  if ((instruction & (1u << 24)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_633:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_632;
  }
  return 0;

autodecoder_arm_monolithic_783:
  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_735;
  }

autodecoder_arm_monolithic_775:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_638;
  }

autodecoder_arm_monolithic_774:
  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_773;
  }

autodecoder_arm_monolithic_430:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_429;
  }

autodecoder_arm_monolithic_420:
  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_419;
  }

autodecoder_arm_monolithic_413:
  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_arm_monolithic_410;
  }

autodecoder_arm_monolithic_412:
  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_arm_monolithic_410;
  }

autodecoder_arm_monolithic_411:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_410;
  }

autodecoder_arm_monolithic_407:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_406;
  }

autodecoder_arm_monolithic_393:
  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_80;
  }

autodecoder_arm_monolithic_392:
  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_80;
  }

autodecoder_arm_monolithic_391:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_390;
  }

autodecoder_arm_monolithic_387:
  if ((instruction & (1u << 3)) == 0)
  {
    goto autodecoder_arm_monolithic_80;
  }

autodecoder_arm_monolithic_386:
  if ((instruction & (1u << 1)) == 0)
  {
    goto autodecoder_arm_monolithic_80;
  }

autodecoder_arm_monolithic_385:
  if ((instruction & (1u << 2)) == 0)
  {
    goto autodecoder_arm_monolithic_80;
  }

autodecoder_arm_monolithic_384:
  if ((instruction & (1u << 0)) == 0)
  {
    goto autodecoder_arm_monolithic_80;
  }

autodecoder_arm_monolithic_383:
  if ((instruction & (1u << 22)) == 0)
  {
    return armLdrexdInstruction;
  }
  return armLdrexhInstruction;



autodecoder_arm_monolithic_390:
  if ((instruction & (1u << 22)) == 0)
  {
    return armStrexdInstruction;
  }
  return armStrexhInstruction;



autodecoder_arm_monolithic_406:
  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_80;
  }

autodecoder_arm_monolithic_405:
  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_80;
  }

autodecoder_arm_monolithic_404:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_403;
  }

autodecoder_arm_monolithic_400:
  if ((instruction & (1u << 3)) == 0)
  {
    goto autodecoder_arm_monolithic_80;
  }

autodecoder_arm_monolithic_399:
  if ((instruction & (1u << 1)) == 0)
  {
    goto autodecoder_arm_monolithic_80;
  }

autodecoder_arm_monolithic_398:
  if ((instruction & (1u << 2)) == 0)
  {
    goto autodecoder_arm_monolithic_80;
  }

autodecoder_arm_monolithic_397:
  if ((instruction & (1u << 0)) == 0)
  {
    goto autodecoder_arm_monolithic_80;
  }

autodecoder_arm_monolithic_396:
  if ((instruction & (1u << 22)) == 0)
  {
    return armLdrexInstruction;
  }
  return armLdrexbInstruction;



autodecoder_arm_monolithic_403:
  if ((instruction & (1u << 22)) == 0)
  {
    return armStrexInstruction;
  }
  return armStrexbInstruction;



autodecoder_arm_monolithic_419:
  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_410;
  }

autodecoder_arm_monolithic_418:
  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_410;
  }

autodecoder_arm_monolithic_417:
  if (instruction & (1u << 9))
  {
    goto autodecoder_arm_monolithic_410;
  }
  goto autodecoder_arm_monolithic_416;

autodecoder_arm_monolithic_429:
  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_410;
  }

autodecoder_arm_monolithic_428:
  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_410;
  }

autodecoder_arm_monolithic_427:
  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_410;
  }

autodecoder_arm_monolithic_426:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_425;
  }

autodecoder_arm_monolithic_410:
  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_80;
  }

autodecoder_arm_monolithic_409:
  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_80;
  }

autodecoder_arm_monolithic_408:
  if (instruction & (1u << 20))
  {
    goto autodecoder_arm_monolithic_80;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");

autodecoder_arm_monolithic_425:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_424;
  }

autodecoder_arm_monolithic_416:
  if (instruction & (1u << 5))
  {
    return 0;
  }

autodecoder_arm_monolithic_415:
  if (instruction & (1u << 6))
  {
    return 0;
  }

autodecoder_arm_monolithic_414:
  if (instruction & (1u << 20))
  {
    return 0;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");

autodecoder_arm_monolithic_424:
  if (instruction & (1u << 5))
  {
    return 0;
  }

autodecoder_arm_monolithic_423:
  if (instruction & (1u << 6))
  {
    return 0;
  }

autodecoder_arm_monolithic_422:
  if (instruction & (1u << 20))
  {
    return 0;
  }
  return swpInstruction;


autodecoder_arm_monolithic_773:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_632;
  }

autodecoder_arm_monolithic_772:
  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_756;
  }

autodecoder_arm_monolithic_764:
  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_756;
  }

autodecoder_arm_monolithic_763:
  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_756;
  }

autodecoder_arm_monolithic_762:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_761;
  }

autodecoder_arm_monolithic_756:
  if ((instruction & (1u << 21)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_750:
  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_749;
  }
  return 0;

autodecoder_arm_monolithic_761:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_481;
  }

autodecoder_arm_monolithic_760:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_474;
  }

autodecoder_arm_monolithic_749:
  if ((instruction & (1u << 6)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_746:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_745:
  if ((instruction & (1u << 22)) == 0)
  {
    return 0;
  }
  return smcInstruction;


autodecoder_arm_monolithic_474:
  if ((instruction & (1u << 6)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_473:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_472:
  if ((instruction & (1u << 22)) == 0)
  {
    return qsubInstruction;
  }
  return qdsubInstruction;



autodecoder_arm_monolithic_481:
  if (instruction & (1u << 5))
  {
    return 0;
  }

autodecoder_arm_monolithic_480:
  if ((instruction & (1u << 6)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_479:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_478:
  if ((instruction & (1u << 22)) == 0)
  {
    return qaddInstruction;
  }
  return qdaddInstruction;



autodecoder_arm_monolithic_638:
  if ((instruction & (1u << 7)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_519:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_518;
  }

autodecoder_arm_monolithic_506:
  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_497;
  }

autodecoder_arm_monolithic_505:
  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_497;
  }

autodecoder_arm_monolithic_504:
  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_497;
  }

autodecoder_arm_monolithic_503:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_502;
  }

autodecoder_arm_monolithic_497:
  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_monolithic_495;
  }

autodecoder_arm_monolithic_496:
  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_80;
  }
  goto autodecoder_arm_monolithic_494;

autodecoder_arm_monolithic_502:
  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_monolithic_501;
  }
  return 0;

autodecoder_arm_monolithic_518:
  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_511;
  }

autodecoder_arm_monolithic_517:
  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_511;
  }

autodecoder_arm_monolithic_516:
  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_511;
  }

autodecoder_arm_monolithic_515:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_514;
  }

autodecoder_arm_monolithic_511:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_510;
  }

autodecoder_arm_monolithic_495:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_494;
  }

autodecoder_arm_monolithic_493:
  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_80;
  }

autodecoder_arm_monolithic_492:
  if (instruction & (1u << 20))
  {
    return armLdrhtInstruction;
  }

autodecoder_arm_monolithic_491:
  if (instruction & (1u << 22))
  {
    return armStrhtInstruction;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");

autodecoder_arm_monolithic_494:
  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_80;
  }
  return 0;

autodecoder_arm_monolithic_510:
  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_80;
  }

autodecoder_arm_monolithic_509:
  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_80;
  }
  goto autodecoder_arm_monolithic_508;

autodecoder_arm_monolithic_514:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_513;
  }

autodecoder_arm_monolithic_501:
  if ((instruction & (1u << 5)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_500:
  if (instruction & (1u << 6))
  {
    return 0;
  }

autodecoder_arm_monolithic_499:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_498;
  }
  return armLdrhtInstruction;


autodecoder_arm_monolithic_498:
  if ((instruction & (1u << 22)) == 0)
  {
    return 0;
  }
  return armStrhtInstruction;


autodecoder_arm_monolithic_513:
  if (instruction & (1u << 5))
  {
    return 0;
  }

autodecoder_arm_monolithic_512:
  if (instruction & (1u << 6))
  {
    return 0;
  }

autodecoder_arm_monolithic_508:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_507:
  if (instruction & (1u << 22))
  {
      printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");
  }
  return 0;

autodecoder_arm_monolithic_735:
  if ((instruction & (1u << 24)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_734:
  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_646;
  }

autodecoder_arm_monolithic_733:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_632;
  }

autodecoder_arm_monolithic_732:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_557;
  }

autodecoder_arm_monolithic_731:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_730;
  }

autodecoder_arm_monolithic_726:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_725;
  }

autodecoder_arm_monolithic_721:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_720:
  if ((instruction & (1u << 22)) == 0)
  {
    return smulwtInstruction;
  }
  return smulttInstruction;



autodecoder_arm_monolithic_725:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_724:
  if ((instruction & (1u << 22)) == 0)
  {
    return smulwbInstruction;
  }
  return smultbInstruction;



autodecoder_arm_monolithic_730:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_536;
  }

autodecoder_arm_monolithic_729:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_728:
  if ((instruction & (1u << 22)) == 0)
  {
    return smlawtInstruction;
  }
  return smulbtInstruction;



autodecoder_arm_monolithic_536:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_535:
  if (instruction & (1u << 22))
  {
    return 0;
  }
  return smlawbInstruction;


autodecoder_arm_monolithic_557:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_556;
  }

autodecoder_arm_monolithic_547:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_546;
  }

autodecoder_arm_monolithic_542:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_541:
  if ((instruction & (1u << 22)) == 0)
  {
    return smlattInstruction;
  }
  return smlalttInstruction;



autodecoder_arm_monolithic_546:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_545:
  if ((instruction & (1u << 22)) == 0)
  {
    return smlatbInstruction;
  }
  return smlaltbInstruction;



autodecoder_arm_monolithic_556:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_555;
  }

autodecoder_arm_monolithic_551:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_550:
  if ((instruction & (1u << 22)) == 0)
  {
    return smlabtInstruction;
  }
  return smlalbtInstruction;



autodecoder_arm_monolithic_555:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_554:
  if ((instruction & (1u << 22)) == 0)
  {
    return smlabbInstruction;
  }
  return smlalbbInstruction;



autodecoder_arm_monolithic_646:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_645;
  }

autodecoder_arm_monolithic_632:
  if ((instruction & (1u << 21)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_631:
  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_monolithic_80;
  }

autodecoder_arm_monolithic_630:
  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_monolithic_80;
  }

autodecoder_arm_monolithic_629:
  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_monolithic_80;
  }

autodecoder_arm_monolithic_628:
  if ((instruction & (1u << 17)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_80:
  if (instruction & (1u << 22))
  {
    return 0;
  }
    printf("Undefined instruction: %#.8x" EOL, instruction);
DIE_NOW(NULL, "autoDecoder (arm): undefined instruction");


autodecoder_arm_monolithic_645:
  if (instruction & (1u << 8))
  {
    return 0;
  }

autodecoder_arm_monolithic_644:
  if (instruction & (1u << 11))
  {
    return 0;
  }

autodecoder_arm_monolithic_643:
  if (instruction & (1u << 10))
  {
    return 0;
  }

autodecoder_arm_monolithic_642:
  if (instruction & (1u << 9))
  {
    return 0;
  }

autodecoder_arm_monolithic_641:
  if (instruction & (1u << 21))
  {
    return 0;
  }

autodecoder_arm_monolithic_600:
  if ((instruction & (1u << 16)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_599:
  if ((instruction & (1u << 19)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_598:
  if ((instruction & (1u << 18)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_597:
  if ((instruction & (1u << 17)) == 0)
  {
    return 0;
  }

autodecoder_arm_monolithic_596:
  if (instruction & (1u << 5))
  {
    return 0;
  }

autodecoder_arm_monolithic_595:
  if (instruction & (1u << 6))
  {
    return 0;
  }

autodecoder_arm_monolithic_594:
  if (instruction & (1u << 20))
  {
    return 0;
  }

autodecoder_arm_monolithic_593:
  if (instruction & (1u << 3))
  {
    return 0;
  }

autodecoder_arm_monolithic_592:
  if (instruction & (1u << 1))
  {
    return 0;
  }

autodecoder_arm_monolithic_591:
  if (instruction & (1u << 2))
  {
    return 0;
  }

autodecoder_arm_monolithic_590:
  if (instruction & (1u << 0))
  {
    return 0;
  }
  return mrsInstruction;



