/*******************************************************************************
 *
 * This file was auto-generated by:
 *
 * autodecoder jam/unknown (debug build)
 * 
 * Built with GNU C++ compiler (gcc 4.7.3)
 * Libraries: CUDD bundled (2.5.0); LEMON bundled (git); Xerces-C++ system
 *
 * WARNING: Do not edit this file, otherwise your changes will be lost.
 * Please edit the decoder specification instead, and generate a new decoder.
 *
 * Options used:
 * Specification:     decoder.xml
 * Number of stages:  1 (monolithic)
 * Type:              g (graph)
 * Exhaustive test:   no
 *
 ******************************************************************************/

  if ((instruction & (1u << 29)) == 0)
  {
    goto autodecoder_arm_monolithic_593;
  }

  if ((instruction & (1u << 30)) == 0)
  {
    goto autodecoder_arm_monolithic_593;
  }

  if ((instruction & (1u << 31)) == 0)
  {
    goto autodecoder_arm_monolithic_593;
  }

  if ((instruction & (1u << 27)) == 0)
  {
    goto autodecoder_arm_monolithic_550;
  }

  if ((instruction & (1u << 15)) == 0)
  {
    goto autodecoder_arm_monolithic_64;
  }

  if (instruction & (1u << 28))
  {
    goto autodecoder_arm_monolithic_3;
  }
  goto autodecoder_arm_monolithic_20;

autodecoder_arm_monolithic_64:
  if (instruction & (1u << 12))
  {
    goto autodecoder_arm_monolithic_29;
  }

  if (instruction & (1u << 13))
  {
    goto autodecoder_arm_monolithic_29;
  }

  if ((instruction & (1u << 14)) == 0)
  {
    goto autodecoder_arm_monolithic_61;
  }

autodecoder_arm_monolithic_29:
  if ((instruction & (1u << 28)) == 0)
  {
    goto autodecoder_arm_monolithic_28;
  }

autodecoder_arm_monolithic_3:
  if (instruction & (1u << 26))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 25))
  {
    handler->barePtr = (void *)(armBlxImmediateInstruction);
    return IRC_REPLACE;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_61:
  if ((instruction & (1u << 28)) == 0)
  {
    goto autodecoder_arm_monolithic_28;
  }

  if (instruction & (1u << 26))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_58;
  }
  handler->barePtr = (void *)(armBlxImmediateInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_58:
  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_57;
  }

  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_41;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_57:
  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_55;
  }

autodecoder_arm_monolithic_41:
  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 9))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 20))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 16)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 19)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 18)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armSrsInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_55:
  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 3))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 2))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 0))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 1))
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armRfeInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_550:
  if ((instruction & (1u << 15)) == 0)
  {
    goto autodecoder_arm_monolithic_549;
  }

  if ((instruction & (1u << 12)) == 0)
  {
    goto autodecoder_arm_monolithic_496;
  }

  if ((instruction & (1u << 13)) == 0)
  {
    goto autodecoder_arm_monolithic_496;
  }

  if ((instruction & (1u << 14)) == 0)
  {
    goto autodecoder_arm_monolithic_496;
  }

  if ((instruction & (1u << 28)) == 0)
  {
    goto autodecoder_arm_monolithic_443;
  }

  if ((instruction & (1u << 26)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_108;
  }

  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_72;
  }

  if (instruction & (1u << 4))
  {
    goto autodecoder_arm_undefined;
  }
  goto autodecoder_arm_monolithic_68;

autodecoder_arm_monolithic_72:
  if (instruction & (1u << 4))
  {
    goto autodecoder_arm_undefined;
  }
  goto autodecoder_arm_monolithic_71;

autodecoder_arm_monolithic_108:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_71;
  }

  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_106;
  }

  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_68;
  }

  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_68;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_68;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_68;
  }

  if (instruction & (1u << 9))
  {
    goto autodecoder_arm_monolithic_68;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_68;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_67;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 16)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 19)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 18)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 17)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 6))
  {
    return IRC_REMOVE;
  }
  goto autodecoder_arm_monolithic_77;

autodecoder_arm_monolithic_106:
  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_68;
  }

  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_68;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_68;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_68;
  }

  if (instruction & (1u << 9))
  {
    goto autodecoder_arm_monolithic_68;
  }

  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_100;
  }

autodecoder_arm_monolithic_68:
  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_undefined;
  }
  goto autodecoder_arm_monolithic_67;

autodecoder_arm_monolithic_100:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_67;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 16)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 19)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 18)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 17)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 6))
  {
    return IRC_REMOVE;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_71:
  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

autodecoder_arm_monolithic_67:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_undefined;
  }
  return IRC_REMOVE;


autodecoder_arm_monolithic_443:
  if (instruction & (1u << 26))
  {
    goto autodecoder_arm_monolithic_194;
  }

  if (instruction & (1u << 25))
  {
    goto autodecoder_arm_monolithic_270;
  }

  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_440;
  }

  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_405;
  }

  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_302;
  }

  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_338;
  }

  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_arm_monolithic_338;
  }

  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_arm_monolithic_338;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_338;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_314;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    return IRC_SAFE;
  }

  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_318;
  }

  if (instruction & (1u << 20))
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 16)) == 0)
  {
    goto autodecoder_arm_monolithic_326;
  }

  if ((instruction & (1u << 19)) == 0)
  {
    goto autodecoder_arm_monolithic_326;
  }

  if ((instruction & (1u << 18)) == 0)
  {
    goto autodecoder_arm_monolithic_326;
  }

  if ((instruction & (1u << 17)) == 0)
  {
    goto autodecoder_arm_monolithic_326;
  }

  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_323;
  }

  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armBkptInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armBlxRegisterInstruction);
  return IRC_REPLACE;

autodecoder_arm_monolithic_338:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_314;
  }
  goto autodecoder_arm_monolithic_337;

autodecoder_arm_monolithic_549:
  if (instruction & (1u << 12))
  {
    goto autodecoder_arm_monolithic_496;
  }

  if (instruction & (1u << 13))
  {
    goto autodecoder_arm_monolithic_496;
  }

  if ((instruction & (1u << 14)) == 0)
  {
    goto autodecoder_arm_monolithic_546;
  }

autodecoder_arm_monolithic_496:
  if (instruction & (1u << 28))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 26))
  {
    goto autodecoder_arm_monolithic_451;
  }

  if (instruction & (1u << 25))
  {
    goto autodecoder_arm_monolithic_461;
  }

  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_492;
  }

  if (instruction & (1u << 4))
  {
    goto autodecoder_arm_monolithic_464;
  }
  goto autodecoder_arm_monolithic_489;

autodecoder_arm_monolithic_546:
  if ((instruction & (1u << 28)) == 0)
  {
    goto autodecoder_arm_monolithic_545;
  }

  if (instruction & (1u << 26))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 25))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_515;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 20))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_monolithic_503;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_515:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 20))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 16)) == 0)
  {
    goto autodecoder_arm_monolithic_510;
  }

autodecoder_arm_monolithic_503:
  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armSetendInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_510:
  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armCpsInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_545:
  if (instruction & (1u << 26))
  {
    goto autodecoder_arm_monolithic_451;
  }

  if (instruction & (1u << 25))
  {
    goto autodecoder_arm_monolithic_461;
  }

  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_492;
  }

  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_541;
  }

autodecoder_arm_monolithic_464:
  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_302;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_462;
  }

autodecoder_arm_monolithic_337:
  if ((instruction & (1u << 21)) == 0)
  {
    return IRC_SAFE;
  }

  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_318;
  }

  if (instruction & (1u << 20))
  {
    return IRC_SAFE;
  }

autodecoder_arm_monolithic_326:
  if ((instruction & (1u << 5)) == 0)
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 6)) == 0)
  {
    return IRC_SAFE;
  }
  handler->barePtr = (void *)(armBkptInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_541:
  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_522;
  }

  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_473;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_473;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_473;
  }

  if (instruction & (1u << 9))
  {
    goto autodecoder_arm_monolithic_473;
  }

  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_483;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSR);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 22))
  {
    handler->barePtr = (void *)(armShiftPCImm);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 20))
  {
    goto autodecoder_arm_monolithic_480;
  }

  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 5))
  {
    handler->barePtr = (void *)(armShiftPCImm);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armShiftPCImm);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 3))
  {
    handler->barePtr = (void *)(armMovPCInstruction);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 2))
  {
    handler->barePtr = (void *)(armMovPCInstruction);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 0))
  {
    handler->barePtr = (void *)(armMovPCInstruction);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 1))
  {
    handler->barePtr = (void *)(armMovPCInstruction);
    return IRC_PATCH_PC;
  }
  return IRC_SAFE;

autodecoder_arm_monolithic_593:
  if ((instruction & (1u << 27)) == 0)
  {
    goto autodecoder_arm_monolithic_592;
  }

  if ((instruction & (1u << 15)) == 0)
  {
    goto autodecoder_arm_monolithic_28;
  }

autodecoder_arm_monolithic_20:
  if (instruction & (1u << 26))
  {
    goto autodecoder_arm_monolithic_10;
  }

  if (instruction & (1u << 25))
  {
    handler->barePtr = (void *)(armBInstruction);
    return IRC_REPLACE;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_monolithic_17;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    handler->barePtr = (void *)(armStmInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armLdmExcRetInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_17:
  if ((instruction & (1u << 20)) == 0)
  {
    handler->barePtr = (void *)(armStmPC);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armLdmInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_28:
  if ((instruction & (1u << 26)) == 0)
  {
    goto autodecoder_arm_monolithic_27;
  }

autodecoder_arm_monolithic_10:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_8;
  }
  handler->barePtr = (void *)(svcInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_8:
  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    handler->barePtr = (void *)(armMcrInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armMrcInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_27:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_26;
  }
  handler->barePtr = (void *)(armBInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_26:
  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_monolithic_25;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    handler->barePtr = (void *)(armStmInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armLdmUserInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_25:
  if (instruction & (1u << 20))
  {
    return IRC_SAFE;
  }
  handler->barePtr = (void *)(armStmPC);
  return IRC_PATCH_PC;


autodecoder_arm_monolithic_592:
  if ((instruction & (1u << 15)) == 0)
  {
    goto autodecoder_arm_monolithic_591;
  }

  if ((instruction & (1u << 12)) == 0)
  {
    goto autodecoder_arm_monolithic_580;
  }

  if ((instruction & (1u << 13)) == 0)
  {
    goto autodecoder_arm_monolithic_580;
  }

  if ((instruction & (1u << 14)) == 0)
  {
    goto autodecoder_arm_monolithic_580;
  }

  if ((instruction & (1u << 26)) == 0)
  {
    goto autodecoder_arm_monolithic_573;
  }

autodecoder_arm_monolithic_194:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_193;
  }

  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_182;
  }

  if (instruction & (1u << 4))
  {
    goto autodecoder_arm_monolithic_126;
  }
  goto autodecoder_arm_monolithic_132;

autodecoder_arm_monolithic_182:
  if (instruction & (1u << 4))
  {
    goto autodecoder_arm_monolithic_173;
  }

  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_monolithic_180;
  }

autodecoder_arm_monolithic_132:
  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_129;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    handler->barePtr = (void *)(armStrPCInstruction);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armLdrRegInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_193:
  if (instruction & (1u << 24))
  {
    goto autodecoder_arm_monolithic_186;
  }

  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_monolithic_191;
  }

autodecoder_arm_monolithic_186:
  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_129;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    handler->barePtr = (void *)(armStrPCInstruction);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armLdrImmInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_573:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_572;
  }

autodecoder_arm_monolithic_270:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_269;
  }

  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_253;
  }

  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_211;
  }

  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_211;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_211;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_211;
  }

  if (instruction & (1u << 9))
  {
    goto autodecoder_arm_monolithic_211;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_205;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_209;
  }

  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_208;
  }

  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 16))
  {
    handler->barePtr = (void *)(armMsrImmInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 19))
  {
    handler->barePtr = (void *)(armMsrImmInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 18))
  {
    handler->barePtr = (void *)(armMsrImmInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 17))
  {
    handler->barePtr = (void *)(armMsrImmInstruction);
    return IRC_REPLACE;
  }

  if ((instruction & (1u << 5)) == 0)
  {
    handler->barePtr = (void *)(armMsrImmInstruction);
    return IRC_REPLACE;
  }

  if ((instruction & (1u << 6)) == 0)
  {
    handler->barePtr = (void *)(armMsrImmInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armDbgInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_253:
  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_211;
  }

  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_211;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_211;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_211;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_248;
  }

autodecoder_arm_monolithic_211:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_205;
  }

  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_monolithic_208;
  }
  goto autodecoder_arm_monolithic_209;

autodecoder_arm_monolithic_248:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_247;
  }

autodecoder_arm_monolithic_205:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_204;
  }

  if (instruction & (1u << 22))
  {
    handler->barePtr = (void *)(armMvnInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armMovInstruction);
  return IRC_REPLACE;

autodecoder_arm_monolithic_247:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_209;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_monolithic_245;
  }

autodecoder_arm_monolithic_208:
  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armMsrImmInstruction);
  return IRC_REPLACE;

autodecoder_arm_monolithic_245:
  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 16))
  {
    handler->barePtr = (void *)(armMsrImmInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 19))
  {
    handler->barePtr = (void *)(armMsrImmInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 18))
  {
    handler->barePtr = (void *)(armMsrImmInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 17))
  {
    handler->barePtr = (void *)(armMsrImmInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 5))
  {
    handler->barePtr = (void *)(armMsrImmInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armMsrImmInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 3))
  {
    handler->barePtr = (void *)(armMsrImmInstruction);
    return IRC_REPLACE;
  }

  if ((instruction & (1u << 2)) == 0)
  {
    goto autodecoder_arm_monolithic_236;
  }

  if (instruction & (1u << 0))
  {
    handler->barePtr = (void *)(armMsrImmInstruction);
    return IRC_REPLACE;
  }

  if ((instruction & (1u << 1)) == 0)
  {
    handler->barePtr = (void *)(armSevInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armMsrImmInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_236:
  if ((instruction & (1u << 0)) == 0)
  {
    goto autodecoder_arm_monolithic_235;
  }

  if ((instruction & (1u << 1)) == 0)
  {
    handler->barePtr = (void *)(armYieldInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armWfiInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_235:
  if ((instruction & (1u << 1)) == 0)
  {
    return IRC_SAFE;
  }
  handler->barePtr = (void *)(armWfeInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_572:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_440;
  }

  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_405;
  }

  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_302;
  }

  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_565;
  }

  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_arm_monolithic_565;
  }

  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_arm_monolithic_565;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_565;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_314;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    return IRC_SAFE;
  }

  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_318;
  }

  if (instruction & (1u << 20))
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 16)) == 0)
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 19)) == 0)
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 18)) == 0)
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 17)) == 0)
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_323;
  }

  if (instruction & (1u << 6))
  {
    return IRC_SAFE;
  }
  handler->barePtr = (void *)(armBlxRegisterInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_323:
  if (instruction & (1u << 6))
  {
    return IRC_SAFE;
  }
  handler->barePtr = (void *)(armBxInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_565:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_564;
  }

autodecoder_arm_monolithic_314:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_204;
  }

  if (instruction & (1u << 22))
  {
    handler->barePtr = (void *)(armMvnInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_307;
  }

  if (instruction & (1u << 6))
  {
    return IRC_SAFE;
  }
  handler->barePtr = (void *)(armLsrInstruction);
  return IRC_REPLACE;

autodecoder_arm_monolithic_405:
  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_404;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_352;
  }
  goto autodecoder_arm_monolithic_356;

autodecoder_arm_monolithic_404:
  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_403;
  }

  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_arm_monolithic_369;
  }

  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_arm_monolithic_369;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_369;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_352;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 22))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 16)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 19)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 18)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 17)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 5)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armBxjInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_403:
  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_369;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_369;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_400;
  }

autodecoder_arm_monolithic_369:
  if ((instruction & (1u << 23)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

autodecoder_arm_monolithic_352:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_204;
  }

  if (instruction & (1u << 22))
  {
    handler->barePtr = (void *)(armMvnInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_307;
  }

  if ((instruction & (1u << 6)) == 0)
  {
    handler->barePtr = (void *)(armLsrInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armRorInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_307:
  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armAsrInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armLslInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_400:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_399;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_204;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_monolithic_380;
  }
  handler->barePtr = (void *)(armMvnInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_380:
  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_375;
  }

  if ((instruction & (1u << 6)) == 0)
  {
    handler->barePtr = (void *)(armLsrInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armRrxInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_375:
  if ((instruction & (1u << 6)) == 0)
  {
    handler->barePtr = (void *)(armMovInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armAsrInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_204:
  if ((instruction & (1u << 22)) == 0)
  {
    handler->barePtr = (void *)(armOrrInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armBicInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_399:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_398;
  }

  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 5))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armMsrRegInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_440:
  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_269;
  }

  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_438;
  }

autodecoder_arm_monolithic_269:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_268;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_260;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    handler->barePtr = (void *)(armAdcInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armRscInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_260:
  if ((instruction & (1u << 22)) == 0)
  {
    handler->barePtr = (void *)(armAddInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armSbcInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_268:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_267;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    handler->barePtr = (void *)(armEorInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armRsbInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_267:
  if ((instruction & (1u << 22)) == 0)
  {
    handler->barePtr = (void *)(armAndInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armSubInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_591:
  if (instruction & (1u << 12))
  {
    goto autodecoder_arm_monolithic_580;
  }

  if (instruction & (1u << 13))
  {
    goto autodecoder_arm_monolithic_580;
  }

  if ((instruction & (1u << 14)) == 0)
  {
    goto autodecoder_arm_monolithic_588;
  }

autodecoder_arm_monolithic_580:
  if (instruction & (1u << 26))
  {
    goto autodecoder_arm_monolithic_451;
  }

  if (instruction & (1u << 25))
  {
    goto autodecoder_arm_monolithic_461;
  }

  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_492;
  }

  if (instruction & (1u << 4))
  {
    goto autodecoder_arm_monolithic_576;
  }

autodecoder_arm_monolithic_489:
  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_488;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_471;
  }

autodecoder_arm_monolithic_356:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_209;
  }

  if (instruction & (1u << 22))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 5))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }
  return IRC_SAFE;

autodecoder_arm_monolithic_588:
  if ((instruction & (1u << 26)) == 0)
  {
    goto autodecoder_arm_monolithic_587;
  }

autodecoder_arm_monolithic_451:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_450;
  }

  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_447;
  }

  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_129;
  }

autodecoder_arm_monolithic_126:
  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_125;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_116;
  }

  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 20))
  {
    goto autodecoder_arm_monolithic_111;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_125:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_124;
  }

autodecoder_arm_monolithic_116:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_115;
  }

  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_undefined;
  }
  goto autodecoder_arm_monolithic_111;

autodecoder_arm_monolithic_115:
  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_114;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_124:
  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_monolithic_122;
  }

  if (instruction & (1u << 20))
  {
    goto autodecoder_arm_monolithic_113;
  }
  return IRC_SAFE;

autodecoder_arm_monolithic_122:
  if (instruction & (1u << 20))
  {
    goto autodecoder_arm_undefined;
  }
  return IRC_SAFE;

autodecoder_arm_monolithic_447:
  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_446;
  }

autodecoder_arm_monolithic_173:
  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_172;
  }

  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_151;
  }

  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_arm_monolithic_151;
  }

  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_arm_monolithic_151;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_151;
  }

  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_146;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_142;
  }

  if (instruction & (1u << 20))
  {
    goto autodecoder_arm_monolithic_139;
  }
  goto autodecoder_arm_monolithic_135;

autodecoder_arm_monolithic_142:
  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 20))
  {
    goto autodecoder_arm_undefined;
  }
  goto autodecoder_arm_monolithic_134;

autodecoder_arm_monolithic_146:
  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_monolithic_144;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

autodecoder_arm_monolithic_144:
  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_111;
  }
  goto autodecoder_arm_monolithic_113;

autodecoder_arm_monolithic_172:
  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_171;
  }

  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_arm_monolithic_151;
  }

  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_arm_monolithic_151;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_151;
  }

  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_159;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_149;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_134;
  }

autodecoder_arm_monolithic_139:
  if ((instruction & (1u << 16)) == 0)
  {
    goto autodecoder_arm_monolithic_135;
  }

  if ((instruction & (1u << 19)) == 0)
  {
    goto autodecoder_arm_monolithic_135;
  }

  if ((instruction & (1u << 18)) == 0)
  {
    goto autodecoder_arm_monolithic_135;
  }

  if ((instruction & (1u << 17)) == 0)
  {
    goto autodecoder_arm_monolithic_135;
  }

autodecoder_arm_monolithic_134:
  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_113;
  }
  return IRC_SAFE;

autodecoder_arm_monolithic_159:
  if (instruction & (1u << 21))
  {
    return IRC_SAFE;
  }

  if (instruction & (1u << 20))
  {
    return IRC_SAFE;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_171:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_170;
  }

autodecoder_arm_monolithic_151:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_monolithic_135;
  }

autodecoder_arm_monolithic_149:
  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 20))
  {
    goto autodecoder_arm_undefined;
  }

autodecoder_arm_monolithic_135:
  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_undefined;
  }
  return IRC_SAFE;

autodecoder_arm_monolithic_170:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_monolithic_164;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_monolithic_167;
  }

  if (instruction & (1u << 20))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_111;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_167:
  if (instruction & (1u << 20))
  {
    goto autodecoder_arm_undefined;
  }

autodecoder_arm_monolithic_164:
  if ((instruction & (1u << 5)) == 0)
  {
    return IRC_SAFE;
  }

autodecoder_arm_monolithic_111:
  if (instruction & (1u << 6))
  {
    return IRC_SAFE;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_446:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_129;
  }

autodecoder_arm_monolithic_180:
  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_monolithic_179;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    handler->barePtr = (void *)(armStrbtInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armLdrbtRegInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_179:
  if ((instruction & (1u << 20)) == 0)
  {
    handler->barePtr = (void *)(armStrtInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armLdrtRegInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_450:
  if (instruction & (1u << 24))
  {
    goto autodecoder_arm_monolithic_129;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_129;
  }

autodecoder_arm_monolithic_191:
  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_monolithic_190;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    return IRC_SAFE;
  }
  handler->barePtr = (void *)(armLdrbtImmInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_190:
  if ((instruction & (1u << 20)) == 0)
  {
    return IRC_SAFE;
  }
  handler->barePtr = (void *)(armLdrtImmInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_129:
  if ((instruction & (1u << 20)) == 0)
  {
    handler->barePtr = (void *)(armStrPCInstruction);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armLdrPCInstruction);
  return IRC_PATCH_PC;


autodecoder_arm_monolithic_587:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_586;
  }

autodecoder_arm_monolithic_461:
  if ((instruction & (1u << 24)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSR);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_459;
  }

  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_monolithic_456;
  }
  handler->barePtr = (void *)(armALUImmRegRSR);
  return IRC_PATCH_PC;

autodecoder_arm_monolithic_459:
  if (instruction & (1u << 21))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }
  goto autodecoder_arm_monolithic_209;

autodecoder_arm_monolithic_586:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_492;
  }

  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_584;
  }

autodecoder_arm_monolithic_576:
  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_575;
  }

autodecoder_arm_monolithic_302:
  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_301;
  }

  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_arm_monolithic_288;
  }

  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_arm_monolithic_288;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_288;
  }

  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_288;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_monolithic_283;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_279;
  }

  if (instruction & (1u << 5))
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 3)) == 0)
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 2)) == 0)
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 0)) == 0)
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 1))
  {
    return IRC_SAFE;
  }
  handler->barePtr = (void *)(armLdrdhPCInstruction);
  return IRC_PATCH_PC;

autodecoder_arm_monolithic_283:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_114;
  }

  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_undefined;
  }

autodecoder_arm_monolithic_77:
  if ((instruction & (1u << 3)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 2)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 0)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 1))
  {
    return IRC_SAFE;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_301:
  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_288;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_288;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_298;
  }

autodecoder_arm_monolithic_288:
  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_287;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_298:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_287;
  }

  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_monolithic_287;
  }

  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 5))
  {
    handler->barePtr = (void *)(armStrPCInstruction);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armSwpInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_575:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_564;
  }

autodecoder_arm_monolithic_462:
  if ((instruction & (1u << 21)) == 0)
  {
    return IRC_SAFE;
  }

autodecoder_arm_monolithic_456:
  if (instruction & (1u << 22))
  {
    return IRC_SAFE;
  }

  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }
  return IRC_SAFE;

autodecoder_arm_monolithic_564:
  if ((instruction & (1u << 21)) == 0)
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    return IRC_SAFE;
  }

autodecoder_arm_monolithic_318:
  if (instruction & (1u << 20))
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 5)) == 0)
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 6)) == 0)
  {
    return IRC_SAFE;
  }
  handler->barePtr = (void *)(armSmcInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_584:
  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_488;
  }

autodecoder_arm_monolithic_522:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_471;
  }

autodecoder_arm_monolithic_209:
  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }
  return IRC_SAFE;

autodecoder_arm_monolithic_488:
  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_473;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_473;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_473;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_484;
  }

autodecoder_arm_monolithic_473:
  if ((instruction & (1u << 23)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

autodecoder_arm_monolithic_471:
  if ((instruction & (1u << 21)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSR);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 22))
  {
    handler->barePtr = (void *)(armShiftPCImm);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armShiftPCImm);
  return IRC_PATCH_PC;

autodecoder_arm_monolithic_484:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_483;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSR);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 22))
  {
    handler->barePtr = (void *)(armShiftPCImm);
    return IRC_PATCH_PC;
  }

autodecoder_arm_monolithic_480:
  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 5))
  {
    handler->barePtr = (void *)(armShiftPCImm);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 6)) == 0)
  {
    handler->barePtr = (void *)(armMovPCInstruction);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armShiftPCImm);
  return IRC_PATCH_PC;



autodecoder_arm_monolithic_483:
  if (instruction & (1u << 21))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

autodecoder_arm_monolithic_398:
  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 16)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 19)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 18)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 17)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 5))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 3))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 2))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 0))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 1))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armMrsInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_492:
  if ((instruction & (1u << 4)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSR);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 7)) == 0)
  {
    return IRC_SAFE;
  }

autodecoder_arm_monolithic_438:
  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_424;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_424;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_424;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_434;
  }

autodecoder_arm_monolithic_424:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_423;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_417;
  }

  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_413;
  }
  goto autodecoder_arm_monolithic_114;

autodecoder_arm_monolithic_417:
  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_416;
  }
  goto autodecoder_arm_monolithic_114;

autodecoder_arm_monolithic_423:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_422;
  }

  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_420;
  }
  goto autodecoder_arm_monolithic_114;

autodecoder_arm_monolithic_422:
  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_287;
  }

autodecoder_arm_monolithic_114:
  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_undefined;
  }

autodecoder_arm_monolithic_113:
  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_undefined;
  }
  return IRC_SAFE;

autodecoder_arm_monolithic_434:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_433;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_416;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_monolithic_428;
  }

autodecoder_arm_monolithic_413:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_412;
  }

  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_408;
  }
  goto autodecoder_arm_monolithic_278;

autodecoder_arm_monolithic_433:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_432;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_monolithic_428;
  }

autodecoder_arm_monolithic_420:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_412;
  }

  if ((instruction & (1u << 5)) == 0)
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }

autodecoder_arm_monolithic_408:
  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armLdrhtImmInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_412:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_278;
  }

  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armStrPCInstruction);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armStrhtInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_428:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_279;
  }

  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_278;
  }

  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armLdrhtRegInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_432:
  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_monolithic_416;
  }

autodecoder_arm_monolithic_287:
  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 5))
  {
    handler->barePtr = (void *)(armStrPCInstruction);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }
  goto autodecoder_arm_undefined;


autodecoder_arm_monolithic_416:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_monolithic_279;
  }

  if (instruction & (1u << 5))
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }
  goto autodecoder_arm_monolithic_278;

autodecoder_arm_monolithic_279:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_278;
  }
  handler->barePtr = (void *)(armStrPCInstruction);
  return IRC_PATCH_PC;


autodecoder_arm_monolithic_278:
  if ((instruction & (1u << 6)) == 0)
  {
    return IRC_SAFE;
  }
  handler->barePtr = (void *)(armLdrdhPCInstruction);
  return IRC_PATCH_PC;




autodecoder_arm_undefined:
  printf("instruction = %#.8x" EOL, instruction);
  DIE_NOW(NULL, "undefined instruction");

