/*******************************************************************************
 *
 * This file was auto-generated by:
 *
 * autodecoder jam/unknown (debug build)
 * 
 * Built with GNU C++ compiler (gcc 4.8.1)
 * Libraries: CUDD bundled (2.5.0); LEMON bundled (git); Xerces-C++ system
 *
 * WARNING: Do not edit this file, otherwise your changes will be lost.
 * Please edit the decoder specification instead, and generate a new decoder.
 *
 * Options used:
 * Specification:     decoder.xml
 * Number of stages:  1 (monolithic)
 * Type:              g (graph)
 * Exhaustive test:   no
 *
 ******************************************************************************/

  if ((instruction & (1u << 29)) == 0)
  {
    goto autodecoder_arm_monolithic_616;
  }

  if ((instruction & (1u << 30)) == 0)
  {
    goto autodecoder_arm_monolithic_616;
  }

  if ((instruction & (1u << 31)) == 0)
  {
    goto autodecoder_arm_monolithic_616;
  }

  if ((instruction & (1u << 26)) == 0)
  {
    goto autodecoder_arm_monolithic_581;
  }

  if ((instruction & (1u << 28)) == 0)
  {
    goto autodecoder_arm_monolithic_132;
  }

  if (instruction & (1u << 27))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 15)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 13)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 14)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 12)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_44;
  }

  if (instruction & (1u << 4))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 24))
  {
    goto autodecoder_arm_monolithic_3;
  }
  goto autodecoder_arm_monolithic_5;

autodecoder_arm_monolithic_44:
  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_43;
  }

  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_5;
  }

  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_3;
  }

  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_3;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_3;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_3;
  }

  if (instruction & (1u << 9))
  {
    goto autodecoder_arm_monolithic_3;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_3;
  }

  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_3;
  }

  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_14;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_2;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 3)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 16)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 19)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 18)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 17)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 0)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 2)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 1)) == 0)
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armClrexInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_43:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_5;
  }

  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_3;
  }

  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_3;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_3;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_3;
  }

  if (instruction & (1u << 9))
  {
    goto autodecoder_arm_monolithic_3;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_3;
  }

  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_3;
  }

autodecoder_arm_monolithic_14:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_2;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 16)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 19)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 18)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    return IRC_REMOVE;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_3:
  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_undefined;
  }
  goto autodecoder_arm_monolithic_2;

autodecoder_arm_monolithic_5:
  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

autodecoder_arm_monolithic_2:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_undefined;
  }
  return IRC_REMOVE;


autodecoder_arm_monolithic_581:
  if ((instruction & (1u << 28)) == 0)
  {
    goto autodecoder_arm_monolithic_580;
  }

  if ((instruction & (1u << 27)) == 0)
  {
    goto autodecoder_arm_monolithic_194;
  }

  if (instruction & (1u << 15))
  {
    goto autodecoder_arm_monolithic_135;
  }

  if (instruction & (1u << 13))
  {
    goto autodecoder_arm_monolithic_135;
  }

  if (instruction & (1u << 14))
  {
    goto autodecoder_arm_monolithic_135;
  }

  if ((instruction & (1u << 12)) == 0)
  {
    goto autodecoder_arm_monolithic_165;
  }

autodecoder_arm_monolithic_135:
  if (instruction & (1u << 25))
  {
    handler->barePtr = (void *)(armBlxImmediateInstruction);
    return IRC_REPLACE;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_165:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_164;
  }
  handler->barePtr = (void *)(armBlxImmediateInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_164:
  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_163;
  }

  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_147;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_163:
  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_161;
  }

autodecoder_arm_monolithic_147:
  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 9))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 20))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 16)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 19)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 18)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armSrsInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_161:
  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 3))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 0))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 2))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 1))
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armRfeInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_194:
  if (instruction & (1u << 15))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 13))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 14))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 12))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 25))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_185;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_undefined;
  }
  goto autodecoder_arm_monolithic_177;

autodecoder_arm_monolithic_185:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_183;
  }

autodecoder_arm_monolithic_177:
  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 20))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_monolithic_173;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_183:
  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 20))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 16)) == 0)
  {
    handler->barePtr = (void *)(armCpsInstruction);
    return IRC_REPLACE;
  }

autodecoder_arm_monolithic_173:
  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armSetendInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_580:
  if (instruction & (1u << 27))
  {
    goto autodecoder_arm_monolithic_207;
  }

  if ((instruction & (1u << 15)) == 0)
  {
    goto autodecoder_arm_monolithic_578;
  }

  if ((instruction & (1u << 13)) == 0)
  {
    goto autodecoder_arm_monolithic_549;
  }

  if ((instruction & (1u << 14)) == 0)
  {
    goto autodecoder_arm_monolithic_549;
  }

  if ((instruction & (1u << 12)) == 0)
  {
    goto autodecoder_arm_monolithic_549;
  }

  if (instruction & (1u << 25))
  {
    goto autodecoder_arm_monolithic_284;
  }

  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_495;
  }

  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_435;
  }

  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_341;
  }

  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_400;
  }

  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_arm_monolithic_400;
  }

  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_arm_monolithic_400;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_400;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_371;
  }

  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_395;
  }

  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_377;
  }
  goto autodecoder_arm_monolithic_385;

autodecoder_arm_monolithic_400:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_371;
  }
  goto autodecoder_arm_monolithic_399;

autodecoder_arm_monolithic_578:
  if (instruction & (1u << 13))
  {
    goto autodecoder_arm_monolithic_549;
  }

  if (instruction & (1u << 14))
  {
    goto autodecoder_arm_monolithic_549;
  }

  if ((instruction & (1u << 12)) == 0)
  {
    goto autodecoder_arm_monolithic_575;
  }

autodecoder_arm_monolithic_549:
  if (instruction & (1u << 25))
  {
    goto autodecoder_arm_monolithic_519;
  }

  if (instruction & (1u << 4))
  {
    goto autodecoder_arm_monolithic_524;
  }
  goto autodecoder_arm_monolithic_547;

autodecoder_arm_monolithic_575:
  if (instruction & (1u << 25))
  {
    goto autodecoder_arm_monolithic_519;
  }

  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_573;
  }

autodecoder_arm_monolithic_524:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_523;
  }

  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_341;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_520;
  }

autodecoder_arm_monolithic_399:
  if ((instruction & (1u << 5)) == 0)
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 6)) == 0)
  {
    return IRC_SAFE;
  }

autodecoder_arm_monolithic_377:
  if ((instruction & (1u << 21)) == 0)
  {
    return IRC_SAFE;
  }

  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_373;
  }

  if (instruction & (1u << 20))
  {
    return IRC_SAFE;
  }
  handler->barePtr = (void *)(armBkptInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_573:
  if ((instruction & (1u << 24)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSR);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_553;
  }

  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_533;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_533;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_533;
  }

  if (instruction & (1u << 9))
  {
    goto autodecoder_arm_monolithic_533;
  }

  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_540;
  }

  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_531;
  }

  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_531;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSR);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 22))
  {
    handler->barePtr = (void *)(armShiftPCImm);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 20))
  {
    goto autodecoder_arm_monolithic_507;
  }

  if (instruction & (1u << 3))
  {
    goto autodecoder_arm_monolithic_507;
  }

  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 0))
  {
    handler->barePtr = (void *)(armMovPCInstruction);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 2))
  {
    handler->barePtr = (void *)(armMovPCInstruction);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 1))
  {
    handler->barePtr = (void *)(armMovPCInstruction);
    return IRC_PATCH_PC;
  }
  return IRC_SAFE;

autodecoder_arm_monolithic_616:
  if ((instruction & (1u << 26)) == 0)
  {
    goto autodecoder_arm_monolithic_615;
  }

autodecoder_arm_monolithic_132:
  if ((instruction & (1u << 27)) == 0)
  {
    goto autodecoder_arm_monolithic_131;
  }

  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_56;
  }

  if (instruction & (1u << 24))
  {
    handler->barePtr = (void *)(svcInstruction);
    return IRC_REPLACE;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    handler->barePtr = (void *)(armMcrInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armMrcInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_56:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(svcInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_131:
  if ((instruction & (1u << 15)) == 0)
  {
    goto autodecoder_arm_monolithic_127;
  }

  if ((instruction & (1u << 13)) == 0)
  {
    goto autodecoder_arm_monolithic_127;
  }

  if ((instruction & (1u << 14)) == 0)
  {
    goto autodecoder_arm_monolithic_127;
  }

  if ((instruction & (1u << 12)) == 0)
  {
    goto autodecoder_arm_monolithic_127;
  }

  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_121;
  }

  if (instruction & (1u << 4))
  {
    goto autodecoder_arm_monolithic_113;
  }

autodecoder_arm_monolithic_121:
  if (instruction & (1u << 24))
  {
    goto autodecoder_arm_monolithic_119;
  }

  if (instruction & (1u << 21))
  {
    return IRC_SAFE;
  }

autodecoder_arm_monolithic_119:
  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_116;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    handler->barePtr = (void *)(armStrPCInstruction);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armLdrInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_127:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_125;
  }

  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_125;
  }

autodecoder_arm_monolithic_113:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_112;
  }

  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_75;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_64;
  }

  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_65;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_75:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_74;
  }

autodecoder_arm_monolithic_64:
  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_62;
  }

  if (instruction & (1u << 21))
  {
    return IRC_SAFE;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_62:
  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 22))
  {
    return IRC_SAFE;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_74:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_73;
  }

  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_undefined;
  }
  goto autodecoder_arm_monolithic_70;

autodecoder_arm_monolithic_73:
  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 22))
  {
    return IRC_SAFE;
  }
  goto autodecoder_arm_monolithic_70;

autodecoder_arm_monolithic_112:
  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_111;
  }

  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_93;
  }

  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_arm_monolithic_93;
  }

  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_arm_monolithic_93;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_93;
  }

  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_90;
  }

  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_85;
  }

  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_82;
  }

  if (instruction & (1u << 20))
  {
    goto autodecoder_arm_monolithic_80;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_90:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_89;
  }

  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_87;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_89:
  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_undefined;
  }
  goto autodecoder_arm_monolithic_87;

autodecoder_arm_monolithic_111:
  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_110;
  }

  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_arm_monolithic_93;
  }

  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_arm_monolithic_93;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_93;
  }

  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_87;
  }

  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_85;
  }

  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    return IRC_SAFE;
  }

autodecoder_arm_monolithic_80:
  if ((instruction & (1u << 16)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 19)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 18)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    return IRC_SAFE;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_87:
  if (instruction & (1u << 21))
  {
    return IRC_SAFE;
  }

autodecoder_arm_monolithic_65:
  if (instruction & (1u << 20))
  {
    return IRC_SAFE;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_110:
  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_109;
  }

autodecoder_arm_monolithic_93:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_undefined;
  }
  goto autodecoder_arm_monolithic_85;

autodecoder_arm_monolithic_109:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_85;
  }

  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 21))
  {
    return IRC_SAFE;
  }
  goto autodecoder_arm_monolithic_70;

autodecoder_arm_monolithic_85:
  if (instruction & (1u << 21))
  {
    return IRC_SAFE;
  }

autodecoder_arm_monolithic_82:
  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_undefined;
  }

autodecoder_arm_monolithic_70:
  if (instruction & (1u << 20))
  {
    goto autodecoder_arm_undefined;
  }
  return IRC_SAFE;

autodecoder_arm_monolithic_125:
  if (instruction & (1u << 24))
  {
    goto autodecoder_arm_monolithic_116;
  }

  if (instruction & (1u << 21))
  {
    return IRC_SAFE;
  }

autodecoder_arm_monolithic_116:
  if ((instruction & (1u << 20)) == 0)
  {
    handler->barePtr = (void *)(armStrPCInstruction);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armLdrPCInstruction);
  return IRC_PATCH_PC;


autodecoder_arm_monolithic_615:
  if ((instruction & (1u << 27)) == 0)
  {
    goto autodecoder_arm_monolithic_614;
  }

autodecoder_arm_monolithic_207:
  if ((instruction & (1u << 15)) == 0)
  {
    goto autodecoder_arm_monolithic_206;
  }

  if (instruction & (1u << 25))
  {
    handler->barePtr = (void *)(armBInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_199;
  }

  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armLdmInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armStmPC);
  return IRC_PATCH_PC;

autodecoder_arm_monolithic_206:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_205;
  }
  handler->barePtr = (void *)(armBInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_205:
  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_monolithic_204;
  }

autodecoder_arm_monolithic_199:
  if ((instruction & (1u << 20)) == 0)
  {
    handler->barePtr = (void *)(armStmInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armLdmInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_204:
  if (instruction & (1u << 20))
  {
    return IRC_SAFE;
  }
  handler->barePtr = (void *)(armStmPC);
  return IRC_PATCH_PC;


autodecoder_arm_monolithic_614:
  if ((instruction & (1u << 15)) == 0)
  {
    goto autodecoder_arm_monolithic_613;
  }

  if ((instruction & (1u << 13)) == 0)
  {
    goto autodecoder_arm_monolithic_603;
  }

  if ((instruction & (1u << 14)) == 0)
  {
    goto autodecoder_arm_monolithic_603;
  }

  if ((instruction & (1u << 12)) == 0)
  {
    goto autodecoder_arm_monolithic_603;
  }

  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_597;
  }

autodecoder_arm_monolithic_284:
  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_283;
  }

  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_255;
  }

  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_224;
  }

  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_224;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_224;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_224;
  }

  if (instruction & (1u << 9))
  {
    goto autodecoder_arm_monolithic_224;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_218;
  }

  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_223;
  }

  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_223;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_222;
  }

  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_221;
  }

  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 16))
  {
    handler->barePtr = (void *)(armMsrInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 19))
  {
    handler->barePtr = (void *)(armMsrInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 18))
  {
    handler->barePtr = (void *)(armMsrInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 17))
  {
    handler->barePtr = (void *)(armMsrInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armDbgInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_283:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_255;
  }

  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_224;
  }

  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_224;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_224;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_224;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_277;
  }

autodecoder_arm_monolithic_224:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_218;
  }
  goto autodecoder_arm_monolithic_223;

autodecoder_arm_monolithic_277:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_218;
  }

  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_223;
  }

  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_274;
  }

autodecoder_arm_monolithic_223:
  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_monolithic_221;
  }
  goto autodecoder_arm_monolithic_222;

autodecoder_arm_monolithic_274:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_222;
  }

  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_221;
  }

  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 3))
  {
    handler->barePtr = (void *)(armMsrInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 16))
  {
    handler->barePtr = (void *)(armMsrInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 19))
  {
    handler->barePtr = (void *)(armMsrInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 18))
  {
    handler->barePtr = (void *)(armMsrInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 17))
  {
    handler->barePtr = (void *)(armMsrInstruction);
    return IRC_REPLACE;
  }

  if ((instruction & (1u << 0)) == 0)
  {
    goto autodecoder_arm_monolithic_265;
  }

  if (instruction & (1u << 2))
  {
    handler->barePtr = (void *)(armMsrInstruction);
    return IRC_REPLACE;
  }

  if ((instruction & (1u << 1)) == 0)
  {
    handler->barePtr = (void *)(armYieldInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armWfiInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_265:
  if ((instruction & (1u << 2)) == 0)
  {
    goto autodecoder_arm_monolithic_264;
  }

  if (instruction & (1u << 1))
  {
    handler->barePtr = (void *)(armMsrInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armSevInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_264:
  if ((instruction & (1u << 1)) == 0)
  {
    return IRC_SAFE;
  }
  handler->barePtr = (void *)(armWfeInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_597:
  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_495;
  }

  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_435;
  }

  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_341;
  }

  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_590;
  }

  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_arm_monolithic_590;
  }

  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_arm_monolithic_590;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_590;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_371;
  }

  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_395;
  }

  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_584;
  }

autodecoder_arm_monolithic_385:
  if ((instruction & (1u << 21)) == 0)
  {
    return IRC_SAFE;
  }

  if (instruction & (1u << 22))
  {
    return IRC_SAFE;
  }

  if (instruction & (1u << 20))
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 16)) == 0)
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 19)) == 0)
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 18)) == 0)
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 17)) == 0)
  {
    return IRC_SAFE;
  }
  handler->barePtr = (void *)(armBlxRegisterInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_395:
  if (instruction & (1u << 6))
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    return IRC_SAFE;
  }

  if (instruction & (1u << 22))
  {
    return IRC_SAFE;
  }

  if (instruction & (1u << 20))
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 16)) == 0)
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 19)) == 0)
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 18)) == 0)
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 17)) == 0)
  {
    return IRC_SAFE;
  }
  handler->barePtr = (void *)(armBxInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_590:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_589;
  }

autodecoder_arm_monolithic_371:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_370;
  }

  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_354;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_217;
  }

  if (instruction & (1u << 22))
  {
    handler->barePtr = (void *)(armMvnInstruction);
    return IRC_REPLACE;
  }
  goto autodecoder_arm_monolithic_345;

autodecoder_arm_monolithic_435:
  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_434;
  }
  goto autodecoder_arm_monolithic_255;

autodecoder_arm_monolithic_495:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_255;
  }

  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_493;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_445;
  }
  goto autodecoder_arm_monolithic_449;

autodecoder_arm_monolithic_493:
  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_492;
  }

  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_arm_monolithic_462;
  }

  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_arm_monolithic_462;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_462;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_445;
  }

  if ((instruction & (1u << 5)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 22))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 16)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 19)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 18)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 17)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armBxjInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_492:
  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_462;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_462;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_489;
  }

autodecoder_arm_monolithic_462:
  if ((instruction & (1u << 23)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

autodecoder_arm_monolithic_445:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_370;
  }

  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_354;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_217;
  }

  if (instruction & (1u << 22))
  {
    handler->barePtr = (void *)(armMvnInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armRorInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_370:
  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_362;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_217;
  }

  if (instruction & (1u << 22))
  {
    handler->barePtr = (void *)(armMvnInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armLslInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_489:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_488;
  }

  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_474;
  }

  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_354;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_217;
  }

  if (instruction & (1u << 22))
  {
    handler->barePtr = (void *)(armMvnInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armRrxInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_354:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_217;
  }

  if (instruction & (1u << 22))
  {
    handler->barePtr = (void *)(armMvnInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armLsrInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_474:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_218;
  }

autodecoder_arm_monolithic_362:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_217;
  }

  if (instruction & (1u << 22))
  {
    handler->barePtr = (void *)(armMvnInstruction);
    return IRC_REPLACE;
  }

  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armAsrInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_218:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_217;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_monolithic_213;
  }
  handler->barePtr = (void *)(armMvnInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_213:
  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armMovInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_217:
  if ((instruction & (1u << 22)) == 0)
  {
    handler->barePtr = (void *)(armOrrInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armBicInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_488:
  if (instruction & (1u << 5))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_485;
  }

autodecoder_arm_monolithic_221:
  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armMsrInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_255:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_254;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_246;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    handler->barePtr = (void *)(armAdcInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armRscInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_246:
  if ((instruction & (1u << 22)) == 0)
  {
    handler->barePtr = (void *)(armAddInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armSbcInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_254:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_253;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    handler->barePtr = (void *)(armEorInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armRsbInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_253:
  if ((instruction & (1u << 22)) == 0)
  {
    handler->barePtr = (void *)(armAndInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armSubInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_613:
  if (instruction & (1u << 13))
  {
    goto autodecoder_arm_monolithic_603;
  }

  if (instruction & (1u << 14))
  {
    goto autodecoder_arm_monolithic_603;
  }

  if ((instruction & (1u << 12)) == 0)
  {
    goto autodecoder_arm_monolithic_610;
  }

autodecoder_arm_monolithic_603:
  if (instruction & (1u << 25))
  {
    goto autodecoder_arm_monolithic_519;
  }

  if (instruction & (1u << 4))
  {
    goto autodecoder_arm_monolithic_601;
  }

autodecoder_arm_monolithic_547:
  if ((instruction & (1u << 24)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSR);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_545;
  }

  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_531;
  }

autodecoder_arm_monolithic_449:
  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_446;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_222;
  }

  if (instruction & (1u << 22))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }
  goto autodecoder_arm_monolithic_222;

autodecoder_arm_monolithic_610:
  if ((instruction & (1u << 25)) == 0)
  {
    goto autodecoder_arm_monolithic_609;
  }

autodecoder_arm_monolithic_519:
  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_518;
  }

  if (instruction & (1u << 24))
  {
    goto autodecoder_arm_monolithic_501;
  }
  handler->barePtr = (void *)(armALUImmRegRSR);
  return IRC_PATCH_PC;

autodecoder_arm_monolithic_518:
  if ((instruction & (1u << 24)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSR);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 7))
  {
    goto autodecoder_arm_monolithic_501;
  }

  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_501;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_501;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_501;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_512;
  }

autodecoder_arm_monolithic_501:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_500;
  }
  goto autodecoder_arm_monolithic_446;

autodecoder_arm_monolithic_512:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_446;
  }

  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_500;
  }

  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_509;
  }

autodecoder_arm_monolithic_500:
  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_monolithic_498;
  }
  handler->barePtr = (void *)(armALUImmRegRSR);
  return IRC_PATCH_PC;

autodecoder_arm_monolithic_509:
  if ((instruction & (1u << 21)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSR);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 22))
  {
    return IRC_SAFE;
  }
  goto autodecoder_arm_monolithic_507;

autodecoder_arm_monolithic_446:
  if (instruction & (1u << 21))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }
  goto autodecoder_arm_monolithic_222;

autodecoder_arm_monolithic_609:
  if ((instruction & (1u << 4)) == 0)
  {
    goto autodecoder_arm_monolithic_608;
  }

autodecoder_arm_monolithic_601:
  if ((instruction & (1u << 24)) == 0)
  {
    goto autodecoder_arm_monolithic_523;
  }

  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_599;
  }

autodecoder_arm_monolithic_341:
  if ((instruction & (1u << 8)) == 0)
  {
    goto autodecoder_arm_monolithic_340;
  }

  if ((instruction & (1u << 10)) == 0)
  {
    goto autodecoder_arm_monolithic_325;
  }

  if ((instruction & (1u << 11)) == 0)
  {
    goto autodecoder_arm_monolithic_325;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_325;
  }

  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_325;
  }

  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_287;
  }

  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_288;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_318;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_monolithic_302;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    handler->barePtr = (void *)(armStrexhInstruction);
    return IRC_REPLACE;
  }

  if ((instruction & (1u << 3)) == 0)
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 0)) == 0)
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 2)) == 0)
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 1)) == 0)
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armLdrexhInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_302:
  if ((instruction & (1u << 20)) == 0)
  {
    handler->barePtr = (void *)(armStrexdInstruction);
    return IRC_REPLACE;
  }

  if ((instruction & (1u << 3)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 0)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 2)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 1)) == 0)
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armLdrexdInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_318:
  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_monolithic_317;
  }

  if ((instruction & (1u << 20)) == 0)
  {
    handler->barePtr = (void *)(armStrexbInstruction);
    return IRC_REPLACE;
  }

  if ((instruction & (1u << 3)) == 0)
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 0)) == 0)
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 2)) == 0)
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 1)) == 0)
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armLdrexbInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_317:
  if ((instruction & (1u << 20)) == 0)
  {
    handler->barePtr = (void *)(armStrexInstruction);
    return IRC_REPLACE;
  }

  if ((instruction & (1u << 3)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 0)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 2)) == 0)
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 1)) == 0)
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armLdrexInstruction);
  return IRC_REPLACE;



autodecoder_arm_monolithic_340:
  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_325;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_325;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_337;
  }

autodecoder_arm_monolithic_325:
  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_287;
  }

  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_288;
  }

  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_322;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_337:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_336;
  }

  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_286;
  }

  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }
  goto autodecoder_arm_monolithic_322;

autodecoder_arm_monolithic_336:
  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_286;
  }

  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 21))
  {
    goto autodecoder_arm_monolithic_322;
  }

  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armSwpInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_599:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_589;
  }

autodecoder_arm_monolithic_520:
  if ((instruction & (1u << 21)) == 0)
  {
    return IRC_SAFE;
  }

autodecoder_arm_monolithic_498:
  if (instruction & (1u << 22))
  {
    return IRC_SAFE;
  }

autodecoder_arm_monolithic_345:
  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }
  return IRC_SAFE;

autodecoder_arm_monolithic_589:
  if ((instruction & (1u << 5)) == 0)
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 6)) == 0)
  {
    return IRC_SAFE;
  }

autodecoder_arm_monolithic_584:
  if ((instruction & (1u << 21)) == 0)
  {
    return IRC_SAFE;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    return IRC_SAFE;
  }

autodecoder_arm_monolithic_373:
  if (instruction & (1u << 20))
  {
    return IRC_SAFE;
  }
  handler->barePtr = (void *)(armSmcInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_523:
  if ((instruction & (1u << 7)) == 0)
  {
    return IRC_SAFE;
  }

autodecoder_arm_monolithic_434:
  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_421;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_421;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_421;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_430;
  }

autodecoder_arm_monolithic_421:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_420;
  }

  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_412;
  }

  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_288;
  }
  return IRC_SAFE;

autodecoder_arm_monolithic_420:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_419;
  }

autodecoder_arm_monolithic_412:
  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_287;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_287;
  }

  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_408;
  }

  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armLdrhtInstruction);
    return IRC_REPLACE;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_287:
  if (instruction & (1u << 22))
  {
    goto autodecoder_arm_monolithic_286;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_419:
  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_418;
  }

autodecoder_arm_monolithic_288:
  if (instruction & (1u << 22))
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }
  goto autodecoder_arm_undefined;

autodecoder_arm_monolithic_430:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_429;
  }

  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_425;
  }

  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }
  return IRC_SAFE;

autodecoder_arm_monolithic_429:
  if ((instruction & (1u << 5)) == 0)
  {
    goto autodecoder_arm_monolithic_428;
  }

autodecoder_arm_monolithic_425:
  if (instruction & (1u << 6))
  {
    goto autodecoder_arm_monolithic_286;
  }

  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_286;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_monolithic_422;
  }

autodecoder_arm_monolithic_408:
  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armLdrhtInstruction);
    return IRC_REPLACE;
  }
  handler->barePtr = (void *)(armStrhtInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_422:
  if ((instruction & (1u << 20)) == 0)
  {
    handler->barePtr = (void *)(armStrPCInstruction);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armLdrhtInstruction);
  return IRC_REPLACE;


autodecoder_arm_monolithic_286:
  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armStrPCInstruction);
  return IRC_PATCH_PC;


autodecoder_arm_monolithic_428:
  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }

autodecoder_arm_monolithic_418:
  if ((instruction & (1u << 21)) == 0)
  {
    goto autodecoder_arm_monolithic_417;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    return IRC_SAFE;
  }

  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armLdrdhPCInstruction);
    return IRC_PATCH_PC;
  }
  return IRC_SAFE;

autodecoder_arm_monolithic_417:
  if ((instruction & (1u << 22)) == 0)
  {
    return IRC_SAFE;
  }

autodecoder_arm_monolithic_322:
  if ((instruction & (1u << 20)) == 0)
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armLdrdhPCInstruction);
  return IRC_PATCH_PC;


autodecoder_arm_monolithic_608:
  if ((instruction & (1u << 24)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSR);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 7)) == 0)
  {
    goto autodecoder_arm_monolithic_545;
  }

autodecoder_arm_monolithic_553:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_531;
  }

autodecoder_arm_monolithic_222:
  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }
  return IRC_SAFE;


autodecoder_arm_monolithic_545:
  if (instruction & (1u << 8))
  {
    goto autodecoder_arm_monolithic_533;
  }

  if (instruction & (1u << 10))
  {
    goto autodecoder_arm_monolithic_533;
  }

  if (instruction & (1u << 11))
  {
    goto autodecoder_arm_monolithic_533;
  }

  if ((instruction & (1u << 9)) == 0)
  {
    goto autodecoder_arm_monolithic_541;
  }

autodecoder_arm_monolithic_533:
  if (instruction & (1u << 23))
  {
    goto autodecoder_arm_monolithic_531;
  }
  handler->barePtr = (void *)(armALUImmRegRSRNoDest);
  return IRC_PATCH_PC;

autodecoder_arm_monolithic_541:
  if ((instruction & (1u << 23)) == 0)
  {
    goto autodecoder_arm_monolithic_540;
  }

  if (instruction & (1u << 5))
  {
    goto autodecoder_arm_monolithic_531;
  }

  if ((instruction & (1u << 6)) == 0)
  {
    goto autodecoder_arm_monolithic_535;
  }

autodecoder_arm_monolithic_531:
  if ((instruction & (1u << 21)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSR);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 22))
  {
    handler->barePtr = (void *)(armShiftPCImm);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 17))
  {
    goto autodecoder_arm_undefined;
  }
  handler->barePtr = (void *)(armShiftPCImm);
  return IRC_PATCH_PC;

autodecoder_arm_monolithic_535:
  if ((instruction & (1u << 21)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSR);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 22)) == 0)
  {
    goto autodecoder_arm_monolithic_507;
  }
  handler->barePtr = (void *)(armShiftPCImm);
  return IRC_PATCH_PC;


autodecoder_arm_monolithic_507:
  if (instruction & (1u << 16))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 19))
  {
    goto autodecoder_arm_undefined;
  }

  if (instruction & (1u << 18))
  {
    goto autodecoder_arm_undefined;
  }

  if ((instruction & (1u << 17)) == 0)
  {
    handler->barePtr = (void *)(armMovPCInstruction);
    return IRC_PATCH_PC;
  }
  goto autodecoder_arm_undefined;



autodecoder_arm_monolithic_540:
  if (instruction & (1u << 5))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 6))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 21))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

autodecoder_arm_monolithic_485:
  if (instruction & (1u << 20))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 3))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 16)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 19)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 18)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if ((instruction & (1u << 17)) == 0)
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 0))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 2))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }

  if (instruction & (1u << 1))
  {
    handler->barePtr = (void *)(armALUImmRegRSRNoDest);
    return IRC_PATCH_PC;
  }
  handler->barePtr = (void *)(armMrsInstruction);
  return IRC_REPLACE;




autodecoder_arm_undefined:
  printf("instruction = %#.8x" EOL, instruction);
  DIE_NOW(NULL, "undefined instruction");

